CREATE OR REPLACE TYPE admsisa.TY_DTOS_DTLLE_SNSTRO FORCE AS OBJECT 
(
  NMRO_SOLICITUD NUMBER(10),
  FECHA_MORA     DATE,
  ESTADO_PAGO    VARCHAR2(50),
  ESTADO_SINIESTRO VARCHAR2(50),
  UBICACION_CASO  VARCHAR2(20),
  SUCURSAL       VARCHAR2(100),
  MESES_DESFASE  NUMBER(10),
  DIAS_DESFASE   NUMBER(10),
  FECHA_DESOCUPA DATE,
  FECHA_CONTRATO DATE,
  FECHA_RETIRO_SINI DATE,
  DIRECCION      VARCHAR2(200),
  CIUDAD         VARCHAR2(100)
)
/