CREATE OR REPLACE TYPE admsisa.ty_datos_ingreso Force  As Object
(
NUMERO_SOLICITUD NUMBER(10),
ESTRATO NUMBER (1),
FECHA_CONTRATO DATE,
FECHA_INGRESO DATE,
AMPAROB_EXISTE_IVA VARCHAR(2),
AMPAROB_PORCENTAJE_IVA NUMBER(4,2),
AMPAROS_HOGAR_METRAJE NUMBER(8,2),
NIT_INMOBILIARIA VARCHAR2(20),
TIPO_AUMENTO VARCHAR2(2),
MONTO_AUMENTO NUMBER(5,2)                          
);
/