CREATE OR REPLACE TYPE admsisa.TY_ESTADO_CUENTA FORCE AS OBJECT 
( 
  CONCEPTO          VARCHAR2(6),
  FECHA_MOVIMIENTO  DATE,
  DEUDA_TOTAL       NUMBER(20,2),
  VALOR_PAGADO_AGENCIA  NUMBER(20,2),
  PAGO_NETO_INQUILINO   NUMBER(20,2),
  SALDO_DEUDA           NUMBER(20,2)  
)
/