
-------------------------------------LISTAS_R
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_ERROR_LISTAS_R', 'C_STG_SIBO.ERR$_LST_RESTRICTIVAS', 'PREFIJO DE TABLA TEMPORAL ERRORES LISTAS_R');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_BAD_LISTAS_R', 'C_STG_SIBO.WTMP_LST_RESTRICTIVAS_EXT_BAD', 'PREFIJO DE TABLA TEMPORAL BAD LISTAS_R');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEM_STAGE_LISTAS_R', 'STG_STAGE.LST_RESTRICTIVAS', 'PREFIJO DE TABLA TEMPORAL STAGE LISTAS_R');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TIPO_RECORD_LISTAS_R', 'LISTAS_R%ROWTYPE', 'VARIABLE DE TIPO ROWTYPE DE LISTAS_R');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TABLA_DE_DESTINO_LISTAS_R', 'STG_SIBO.LISTAS_R', 'TABLA DE NEGOCIO LISTAS RESTRICITVAS');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('COLUMNAS_TABLA_DESTINO_LISTAS_R', '1 AS IDLISTASR, 1 AS IDCARGUE, TIPO_IDENTIFICACION AS TIPOIDENTIFICACION,  NRO_IDENTIFICACION AS IDENTIFICACION,  IND_NODESEADO AS IDENTIFICADORNODESEADO', 'CAMPOS PARA EL SELECT DE LISTAS_R');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CURSORES_CADENA_LISTAS_R', 
'TIPO_RECORD.TIPOIDENTIFICACION || '','' || TIPO_RECORD.IDENTIFICACION || '','' || ''NVL('''''' || TIPO_RECORD.IDENTIFICADORNODESEADO || '''''',000)'';', 
'CADENA AUXILIAR PARA INSERT DE LISTAS RESTRITIVAS');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CADENA_CONCATENA_ERROR_LISTAS_R', 'TIPOIDENTIFICACION || ''''|'''' || IDENTIFICACION || ''''|'''' ||  IDENTIFICADORNODESEADO, NVL(DESCRIPCION , ''''SIN DESCRIPCION'''')', 'CADENA AUXILIAR PARA INSERT ERROR EN ERROR CARGUE LINEA');
COMMIT;

--PRELIQUIDACION
-------------------------------------UARIV
/*
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_ERROR_UARIV', 'ERR$_PRELIQ_GENERICO', 'PREFIJO DE TABLA TEMPORAL ERRORES PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_BAD_UARIV', 'WTMP_PRELIQ_GENERICO_EXT_BAD', 'PREFIJO DE TABLA TEMPORAL BAD PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEM_STAGE_UARIV', 'PRELIQ_GENERICO', 'PREFIJO DE TABLA TEMPORAL STAGE PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TIPO_RECORD_UARIV', 'PRELIQ_GENERICO%ROWTYPE', 'VARIABLE DE TIPO ROWTYPE DE PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TABLA_DE_DESTINO_UARIV', 'PRELIQ_UARIV', 'TABLA DE NEGOCIO OTRAS PRELIQUIDACIONES');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('COLUMNAS_TABLA_DESTINO_UARIV', 
'1 AS IDULTIMAPRELIQUIDACION, 
1 AS IDCARGUE,
CODMUNICIPIO,
DEPARTAMENTO,
MUNICIPIO,
CODBENEFICIARIO,
NOMBRE1,
NOMBRE2,
APE1_PROG AS APELLIDO1,
APE2_PROG AS APELLIDO2,
TIPO_ID   AS TIPOID,
DOCUMENTO,
TELEFONO,
CELULAR,
DIRECCION,
CORREOELECTRONICO,
FECHANACIMIENTO,
FECHAEXPEDICION,
SEXO,
VALOR_TOTAL',  
'CAMPOS PARA EL SELECT DE PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CURSORES_CADENA_UARIV', 
'NVL(TIPO_RECORD.CODMUNICIPIO,'') || '''''','''''' || NVL(TIPO_RECORD.DEPARTAMENTO,'') || '''''','''''' || NVL(TIPO_RECORD.MUNICIPIO,'') || '''''','''''' || NVL(TIPO_RECORD.CODBENEFICIARIO,'') || '''''','''''' || NVL(TIPO_RECORD.NOMBRE1,'') || '''''','''''' || NVL(TIPO_RECORD.NOMBRE2,'') || '''''','''''' || NVL(TIPO_RECORD.APELLIDO1,'') || '''''','''''' || NVL(TIPO_RECORD.APELLIDO2,'') || '''''','''''' || NVL(TIPO_RECORD.TIPOID,'') || '''''','' || NVL(TIPO_RECORD.DOCUMENTO,'') || '','' || NVL(TIPO_RECORD.TELEFONO,'') || '','' || NVL(TIPO_RECORD.CELULAR,'') || '','''''' || NVL(TIPO_RECORD.DIRECCION,'') || '''''','''''' || NVL(TIPO_RECORD.CORREOELECTRONICO,'')  || '''''','''''' || NVL(TIPO_RECORD.FECHANACIMIENTO,'')  || '''''','''''' || NVL(TIPO_RECORD.FECHAEXPEDICION,'') || '''''','''''' || NVL(TIPO_RECORD.SEXO,'') || '''''','' || NVL(TIPO_RECORD.VALORTOTAL,0);', 
'CADENA AUXILIAR PARA INSERT DE OTRAS PRELIQUIDACIONES');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CADENA_CONCATENA_ERROR_UARIV', 
'NVL(CODMUNICIPIO,NULL) ||
''''|'''' || NVL(DEPARTAMENTO,NULL) || 
''''|'''' || NVL(MUNICIPIO,NULL) || 
''''|'''' || NVL(CODBENEFICIARIO,NULL) || 
''''|'''' || NVL(NOMBRE1,NULL) || 
''''|'''' || NVL(NOMBRE2,NULL) || 
''''|'''' || NVL(APELLIDO1,NULL) || 
''''|'''' || NVL(APELLIDO2,NULL) || 
''''|'''' || NVL(TIPOID,NULL) || 
''''|'''' || NVL(DOCUMENTO,NULL) || 
''''|'''' || NVL(TELEFONO,NULL) || 
''''|'''' || NVL(CELULAR,NULL) || 
''''|'''' || NVL(DIRECCION,NULL) || 
''''|'''' || NVL(CORREOELECTRONICO,NULL)  || 
''''|'''' || NVL(FECHANACIMIENTO,NULL)  || 
''''|'''' || NVL(FECHAEXPEDICION,NULL) || 
''''|'''' || NVL(SEXO,NULL) || 
''''|'''' || NVL(VALORTOTAL,0) LINEA, NVL(DESCRIPCION , ''''SIN DESCRIPCION'''')', 
'CADENA AUXILIAR PARA INSERT ERROR UARIV EN ERROR CARGUE LINEA');
COMMIT;
*/
-------------------------------------MFEA

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_ERROR_MFEA', 'C_STG_SIBO.ERR$_PRELIQ_GENERICO', 'PREFIJO DE TABLA TEMPORAL ERRORES PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_BAD_MFEA', 'C_STG_SIBO.WTMP_PRELIQ_GENERICO_EXT_BAD', 'PREFIJO DE TABLA TEMPORAL BAD PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEM_STAGE_MFEA', 'STG_STAGE.PRELIQ_GENERICO', 'PREFIJO DE TABLA TEMPORAL STAGE PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TIPO_RECORD_MFEA', 'PRELIQ_GENERICO%ROWTYPE', 'VARIABLE DE TIPO ROWTYPE DE PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TABLA_DE_DESTINO_MFEA', 'STG_SIBO.PRELIQ_MFEA', 'TABLA DE NEGOCIO OTRAS PRELIQUIDACIONES');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('COLUMNAS_TABLA_DESTINO_MFEA', 
'1 AS IDULTIMAPRELIQUIDACION, 
1 AS IDCARGUE,
CODMUNICIPIO,
DEPARTAMENTO,
MUNICIPIO,
CODBENEFICIARIO,
NOMBRE1,
NOMBRE2,
APE1_PROG AS APELLIDO1,
APE2_PROG AS APELLIDO2,
TIPO_ID   AS TIPOID,
DOCUMENTO,
TELEFONO,
CELULAR,
DIRECCION,
CORREOELECTRONICO,
FECHANACIMIENTO,
FECHAEXPEDICION,
SEXO,
VALOR_TOTAL', 
'CAMPOS PARA EL SELECT DE PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CURSORES_CADENA_MFEA', 'NVL(TIPO_RECORD.CODMUNICIPIO,NULL) || '''''','''''' || NVL(TIPO_RECORD.DEPARTAMENTO,NULL) || '''''','''''' || NVL(TIPO_RECORD.MUNICIPIO,NULL) || '''''','''''' || 
NVL(TIPO_RECORD.CODBENEFICIARIO,NULL) || '''''','''''' || NVL(TIPO_RECORD.NOMBRE1,NULL) || '''''','''''' || NVL(TIPO_RECORD.NOMBRE2,NULL) || '''''','''''' || 
NVL(TIPO_RECORD.APELLIDO1,NULL) || '''''','''''' || NVL(TIPO_RECORD.APELLIDO2,NULL) || '''''','''''' || NVL(TIPO_RECORD.TIPOID,NULL) || '''''','' || 
NVL(TIPO_RECORD.DOCUMENTO,NULL) || '','''''' || NVL(TIPO_RECORD.TELEFONO,null) || '''''','''''' || NVL(TIPO_RECORD.CELULAR,null) || '''''','''''' || NVL(TIPO_RECORD.DIRECCION,NULL) || '''''','''''' || 
NVL(TIPO_RECORD.CORREOELECTRONICO,NULL)  || '''''','''''' || NVL(TIPO_RECORD.FECHANACIMIENTO,NULL)  || '''''','''''' || NVL(TIPO_RECORD.FECHAEXPEDICION,NULL) || '''''','''''' || 
NVL(TIPO_RECORD.SEXO,NULL) || '''''','' || TIPO_RECORD.VALORTOTAL;', 'CADENA AUXILIAR PARA INSERT DE MAS FAMILIAS EN ACCIÓN');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CADENA_CONCATENA_ERROR_MFEA', 
'NVL(CODMUNICIPIO,NULL) ||
''''|'''' || NVL(DEPARTAMENTO,NULL) || 
''''|'''' || NVL(MUNICIPIO,NULL) || 
''''|'''' || NVL(CODBENEFICIARIO,NULL) || 
''''|'''' || NVL(NOMBRE1,NULL) || 
''''|'''' || NVL(NOMBRE2,NULL) || 
''''|'''' || NVL(APELLIDO1,NULL) || 
''''|'''' || NVL(APELLIDO2,NULL) || 
''''|'''' || NVL(TIPOID,NULL) || 
''''|'''' || NVL(DOCUMENTO,NULL) || 
''''|'''' || NVL(TELEFONO,NULL) || 
''''|'''' || NVL(CELULAR,NULL) || 
''''|'''' || NVL(DIRECCION,NULL) || 
''''|'''' || NVL(CORREOELECTRONICO,NULL)  || 
''''|'''' || NVL(FECHANACIMIENTO,NULL)  || 
''''|'''' || NVL(FECHAEXPEDICION,NULL) || 
''''|'''' || NVL(SEXO,NULL) || 
''''|'''' || NVL(VALORTOTAL,0) LINEA, NVL(DESCRIPCION , ''''SIN DESCRIPCION'''')', 
'CADENA AUXILIAR PARA INSERT ERROR UARIV EN ERROR CARGUE LINEA');
COMMIT;

-------------------------------------OTROS
--C_STG_SIBO.ERR$_PRELIQ_GENERICO
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_ERROR_OTROS', 'C_STG_SIBO.ERR$_PRELIQ_GENERICO', 'PREFIJO DE TABLA TEMPORAL ERRORES PRELIQ_GENERICO');
COMMIT;
---C_STG_SIBO.WTMP_PRELIQ_GENERICO_EXT_BAD
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_BAD_OTROS', 'C_STG_SIBO.WTMP_PRELIQ_GENERICO_EXT_BAD', 'PREFIJO DE TABLA TEMPORAL BAD PRELIQ_GENERICO');
COMMIT;
--STG_STAGE.PRELIQ_GENERICO
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEM_STAGE_OTROS', 'STG_STAGE.PRELIQ_GENERICO', 'PREFIJO DE TABLA TEMPORAL STAGE PRELIQ_GENERICO');
COMMIT;
--PRELIQ_GENERICO%ROWTYPE
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TIPO_RECORD_OTROS', 'PRELIQ_GENERICO%ROWTYPE', 'VARIABLE DE TIPO ROWTYPE DE PRELIQ_GENERICO');
COMMIT;
--STG_SIBO.PRELIQ_OTROS
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TABLA_DE_DESTINO_OTROS', 'STG_SIBO.PRELIQ_OTROS', 'TABLA DE NEGOCIO OTRAS PRELIQUIDACIONES');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('COLUMNAS_TABLA_DESTINO_OTROS', 
'1 AS IDULTIMAPRELIQUIDACION, 
1 AS IDCARGUE,
CODMUNICIPIO,
DEPARTAMENTO,
MUNICIPIO,
CODBENEFICIARIO,
NOMBRE1,
NOMBRE2,
APE1_PROG AS APELLIDO1,
APE2_PROG AS APELLIDO2,
TIPO_ID   AS TIPOID,
DOCUMENTO,
TELEFONO,
CELULAR,
DIRECCION,
CORREOELECTRONICO,
FECHANACIMIENTO,
FECHAEXPEDICION,
SEXO,
VALOR_TOTAL',  
'CAMPOS PARA EL SELECT DE PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CURSORES_CADENA_OTROS', 'NVL(TIPO_RECORD.CODMUNICIPIO,NULL) || '''''','''''' || NVL(TIPO_RECORD.DEPARTAMENTO,NULL) || '''''','''''' || NVL(TIPO_RECORD.MUNICIPIO,NULL) || '''''','''''' || 
NVL(TIPO_RECORD.CODBENEFICIARIO,NULL) || '''''','''''' || NVL(TIPO_RECORD.NOMBRE1,NULL) || '''''','''''' || NVL(TIPO_RECORD.NOMBRE2,NULL) || '''''','''''' || 
NVL(TIPO_RECORD.APELLIDO1,NULL) || '''''','''''' || NVL(TIPO_RECORD.APELLIDO2,NULL) || '''''','''''' || NVL(TIPO_RECORD.TIPOID,NULL) || '''''','' || 
NVL(TIPO_RECORD.DOCUMENTO,NULL) || '','''''' || NVL(TIPO_RECORD.TELEFONO,null) || '''''','''''' || NVL(TIPO_RECORD.CELULAR,null) || '''''','''''' || NVL(TIPO_RECORD.DIRECCION,NULL) || '''''','''''' || 
NVL(TIPO_RECORD.CORREOELECTRONICO,NULL)  || '''''','''''' || NVL(TIPO_RECORD.FECHANACIMIENTO,NULL)  || '''''','''''' || NVL(TIPO_RECORD.FECHAEXPEDICION,NULL) || '''''','''''' || 
NVL(TIPO_RECORD.SEXO,NULL) || '''''','' || TIPO_RECORD.VALORTOTAL;', 'CADENA AUXILIAR PARA INSERT DE OTRAS PRELIQUIDACIONES');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CADENA_CONCATENA_ERROR_OTROS', 
'NVL(CODMUNICIPIO,NULL) ||
''''|'''' || NVL(DEPARTAMENTO,NULL) || 
''''|'''' || NVL(MUNICIPIO,NULL) || 
''''|'''' || NVL(CODBENEFICIARIO,NULL) || 
''''|'''' || NVL(NOMBRE1,NULL) || 
''''|'''' || NVL(NOMBRE2,NULL) || 
''''|'''' || NVL(APELLIDO1,NULL) || 
''''|'''' || NVL(APELLIDO2,NULL) || 
''''|'''' || NVL(TIPOID,NULL) || 
''''|'''' || NVL(DOCUMENTO,NULL) || 
''''|'''' || NVL(TELEFONO,NULL) || 
''''|'''' || NVL(CELULAR,NULL) || 
''''|'''' || NVL(DIRECCION,NULL) || 
''''|'''' || NVL(CORREOELECTRONICO,NULL)  || 
''''|'''' || NVL(FECHANACIMIENTO,NULL)  || 
''''|'''' || NVL(FECHAEXPEDICION,NULL) || 
''''|'''' || NVL(SEXO,NULL) || 
''''|'''' || NVL(VALORTOTAL,0) LINEA, NVL(DESCRIPCION , ''''SIN DESCRIPCION'''')', 
'CADENA AUXILIAR PARA INSERT ERROR UARIV EN ERROR CARGUE LINEA');
COMMIT;

-------------------------------------SALDOS

--PREFIJO_TABLA_TEMP_ERROR_SALDOS	C_STG_SIBO.ERR$_SALDOS
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_ERROR_SALDOS', 'C_STG_SIBO.ERR$_SALDOS', 'PREFIJO DE TABLA TEMPORAL ERRORES SALDOS');
COMMIT;

--PREFIJO_TABLA_TEMP_BAD_SALDOS	C_STG_SIBO.WTMP_SALDOS_EXT_BAD
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_BAD_SALDOS', 'C_STG_SIBO.WTMP_SALDOS_EXT_BAD', 'PREFIJO DE TABLA TEMPORAL BAD SALDOS');
COMMIT;

--PREFIJO_TABLA_TEM_STAGE_SALDOS	STG_STAGE.SALDOS
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEM_STAGE_SALDOS', 'STG_STAGE.SALDOS', 'PREFIJO DE TABLA TEMPORAL STAGE SALDOS');
COMMIT;

--TIPO_RECORD_SALDOS	SALDOS%ROWTYPE 
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TIPO_RECORD_SALDOS', 'SALDOS%ROWTYPE', 'VARIABLE DE TIPO ROWTYPE DE SALDOS');
COMMIT;

--TABLA_DE_DESTINO_SALDOS	STG_SIBO.SALDOS
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TABLA_DE_DESTINO_SALDOS', 'STG_SIBO.SALDOS', 'TABLA DE NEGOCIO SALDOS');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('COLUMNAS_TABLA_DESTINO_SALDOS', 
'1 AS IDSALDOS, 1 AS IDCARGUE, BIN, NIT_EMPRESA  AS NITEMPRESA, NUM_TARJETA  AS IDDAVIPLATA, MIEMBRO, NOMBRE_TITULAR  AS NOMBRETITULAR, SALDO_DISPONIBLE  AS SALDODISPONIBLE, ESTADO_TARJETA  AS ESTADOTARJETA, DESCRIPCION_ESTADO  AS DESCRIPCIONESTADO, SUBTIPO, TIPO_DOCUMENTO  AS TIPOID, NUMERO_DOCUMENTO  AS DOCUMENTO, ORIGEN_CREACION  AS ORIGENCREACION', 
'CAMPOS PARA EL SELECT DE SALDOS');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CURSORES_CADENA_SALDOS'
,'NVL(TIPO_RECORD.BIN,NULL) || '''''','' || NVL(TIPO_RECORD.NITEMPRESA,NULL) || '','' || NVL(TIPO_RECORD.IDDAVIPLATA,NULL) || '','' || 
	NVL(TIPO_RECORD.MIEMBRO,NULL) || '','''''' || NVL(TIPO_RECORD.NOMBRETITULAR,NULL) || '''''','' || NVL(TIPO_RECORD.SALDODISPONIBLE,NULL) || '','''''' || 
	NVL(TIPO_RECORD.ESTADOTARJETA,NULL) || '''''','''''' || NVL(TIPO_RECORD.DESCRIPCIONESTADO,NULL) || '''''','''''' || NVL(TIPO_RECORD.SUBTIPO,NULL) || '''''','''''' || 
	NVL(TIPO_RECORD.TIPOID,NULL) || '''''','' || NVL(TIPO_RECORD.DOCUMENTO,NULL) || '','''''' || NVL(TIPO_RECORD.ORIGENCREACION,NULL) || '''''''';'
, 'CADENA AUXILIAR PARA INSERT DE SALDOS');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CADENA_CONCATENA_ERROR_SALDOS', 'NVL(BIN,NULL) || 
''''|'''' || NVL(NITEMPRESA,NULL) || 
''''|'''' || NVL(MUNICIPIO,NULL) || 
''''|'''' || NVL(IDDAVIPLATA,NULL) || 
''''|'''' || NVL(MIEMBRO,NULL) || 
''''|'''' || NVL(NOMBRETITULAR,NULL) || 
''''|'''' || NVL(SALDODISPONIBLE,NULL) || 
''''|'''' || NVL(ESTADOTARJETA,NULL) || 
''''|'''' || NVL(DESCRIPCIONESTADO,NULL) || 
''''|'''' || NVL(SUBTIPO,NULL) || 
''''|'''' || NVL(TIPOID,NULL) || 
''''|'''' || NVL(DOCUMENTO,NULL) || 
''''|'''' || NVL(ORIGENCREACION,NULL) LINEA, NVL(DESCRIPCION , ''''SIN DESCRIPCION'''')',
'CADENA AUXILIAR PARA INSERT ERROR EN ERROR CARGUE LINEA');
COMMIT;

-------------------------------------
UPDATE PARAMETROS_SIBO 
SET VALOR_PARAMETRO = 'TIPO_IDENTIFICACION || ''''|'''' || NRO_IDENTIFICACION || ''''|'''' ||  IND_NODESEADO, NVL(ORA_ERR_MESG$ , ''''SIN DESCRIPCION'''')' 
WHERE 
NOMBRE_PARAMETRO = 'CADENA_CONCATENA_ERROR_LISTAS_R';

UPDATE PARAMETROS_SIBO 
SET VALOR_PARAMETRO = 
'NVL(CODMUNICIPIO,NULL) ||
''''|'''' || NVL(DEPARTAMENTO,NULL) || 
''''|'''' || NVL(MUNICIPIO,NULL) || 
''''|'''' || NVL(CODBENEFICIARIO,NULL) || 
''''|'''' || NVL(NOMBRE1,NULL) || 
''''|'''' || NVL(NOMBRE2,NULL) || 
''''|'''' || NVL(APE1_PROG,NULL) || 
''''|'''' || NVL(APE2_PROG,NULL) || 
''''|'''' || NVL(TIPO_ID,NULL) || 
''''|'''' || NVL(DOCUMENTO,NULL) || 
''''|'''' || NVL(TELEFONO,NULL) || 
''''|'''' || NVL(CELULAR,NULL) || 
''''|'''' || NVL(DIRECCION,NULL) || 
''''|'''' || NVL(CORREOELECTRONICO,NULL)  || 
''''|'''' || NVL(FECHANACIMIENTO,NULL)  || 
''''|'''' || NVL(FECHAEXPEDICION,NULL) || 
''''|'''' || NVL(SEXO,NULL) || 
''''|'''' || NVL(VALOR_TOTAL,0) LINEA,  NVL(ORA_ERR_MESG$ , ''''SIN DESCRIPCION'''') DESCRIPCIONERROR'
WHERE 
NOMBRE_PARAMETRO = 'CADENA_CONCATENA_ERROR_MFEA';

UPDATE PARAMETROS_SIBO 
SET VALOR_PARAMETRO = 
'NVL(CODMUNICIPIO,NULL) ||
''''|'''' || NVL(DEPARTAMENTO,NULL) || 
''''|'''' || NVL(MUNICIPIO,NULL) || 
''''|'''' || NVL(CODBENEFICIARIO,NULL) || 
''''|'''' || NVL(NOMBRE1,NULL) || 
''''|'''' || NVL(NOMBRE2,NULL) || 
''''|'''' || NVL(APE1_PROG,NULL) || 
''''|'''' || NVL(APE2_PROG,NULL) || 
''''|'''' || NVL(TIPO_ID,NULL) || 
''''|'''' || NVL(DOCUMENTO,NULL) || 
''''|'''' || NVL(TELEFONO,NULL) || 
''''|'''' || NVL(CELULAR,NULL) || 
''''|'''' || NVL(DIRECCION,NULL) || 
''''|'''' || NVL(CORREOELECTRONICO,NULL)  || 
''''|'''' || NVL(FECHANACIMIENTO,NULL)  || 
''''|'''' || NVL(FECHAEXPEDICION,NULL) || 
''''|'''' || NVL(SEXO,NULL) || 
''''|'''' || NVL(VALOR_TOTAL,0) LINEA,  NVL(ORA_ERR_MESG$ , ''''SIN DESCRIPCION'''') DESCRIPCIONERROR'
WHERE 
NOMBRE_PARAMETRO = 'CADENA_CONCATENA_ERROR_OTROS';

--INSERT PARA AGREGAR ARCHIVOS DE CARGUE EN EL SISTEMA
INSERT INTO TIPO_ARCHIVO 
  (
    NOMBRETIPOARCHIVO,
    SEPARADOR,
    TABLAINSERCION,
    IDENTIFICADOR,
    SECUENCIA
  )
VALUES ('LISTAS RESTRICTIVAS', ';', 'LISTAS_R', 1, 'SEQ_LISTASR');
COMMIT;

INSERT INTO TIPO_ARCHIVO 
  (
    NOMBRETIPOARCHIVO,
    SEPARADOR,
    TABLAINSERCION,
    IDENTIFICADOR,
    SECUENCIA
  )
VALUES ('PRELIQUIDACION UARIV', ';', 'UARIV', 2, 'SEQ_UARIV');
COMMIT;

INSERT INTO TIPO_ARCHIVO 
  (
    NOMBRETIPOARCHIVO,
    SEPARADOR,
    TABLAINSERCION,
    IDENTIFICADOR,
    SECUENCIA
  )
VALUES ('PRELIQUIDACION MFEA', ';', 'MFEA', 3, '	SEQ_MFEA');
COMMIT;

INSERT INTO TIPO_ARCHIVO 
  (
    NOMBRETIPOARCHIVO,
    SEPARADOR,
    TABLAINSERCION,
    IDENTIFICADOR,
    SECUENCIA
  )
VALUES ('PRELIQUIDACION OTROS', ';', 'OTROS', 4, 'SEQ_OTROS');
COMMIT;

INSERT INTO STG_SIBO.TIPO_ARCHIVO (NOMBRETIPOARCHIVO, SEPARADOR, TABLAINSERCION, IDENTIFICADOR, SECUENCIA) 
VALUES ('SALDOS', ';', 'SALDOS', '5', 'SEQ_SALDOS');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
values ('NIT_EMPRESA','8608008602','Nit de la empresa para reporte dispersion');

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM)
VALUES ('FTP_GENERADO_DISPERSION','/export/home/crmcarga/dispersionDaviplata/generados','Ruta remota generados Dispersion');

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM)
VALUES ('LOCAL_GENERADO_DISPERSION','C:\\generadosDispersion\\','Ruta local generados Dispersion');

INSERT INTO "STG_SIBO"."ESTADO_PAGO" (ID_EST_PAGO, DES_EST_PAGO) VALUES ('1', 'En proceso');
INSERT INTO "STG_SIBO"."ESTADO_PAGO" (ID_EST_PAGO, DES_EST_PAGO) VALUES ('2', 'Generado');
INSERT INTO "STG_SIBO"."ESTADO_PAGO" (ID_EST_PAGO, DES_EST_PAGO) VALUES ('3', 'Regenerado');
INSERT INTO "STG_SIBO"."ESTADO_PAGO" (ID_EST_PAGO, DES_EST_PAGO) VALUES ('4', 'Detenido');
INSERT INTO "STG_SIBO"."ESTADO_PAGO" (ID_EST_PAGO, DES_EST_PAGO) VALUES ('5', 'Transmitido'); 

insert into ESTADO_PROCESO (ID_ESTADO,DES_ESTADO) values (0,'Disponible');
insert into ESTADO_PROCESO (ID_ESTADO,DES_ESTADO) values (1,'Preliquidado');
insert into ESTADO_PROCESO (ID_ESTADO,DES_ESTADO) values (2,'Autorizado');
insert into ESTADO_PROCESO (ID_ESTADO,DES_ESTADO) values (3,'Rechazado');
insert into ESTADO_PROCESO (ID_ESTADO,DES_ESTADO) values (4,'En proceso de pago');
insert into ESTADO_PROCESO (ID_ESTADO,DES_ESTADO) values (5,'Procesado');
