--   Diseñó     Alfonso Pimienta
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE PRELIQ_GENERICO' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE LST_RESTRICTIVAS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE WTMP_LST_RESTRICTIVAS_EXT_BAD' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE WTMP_PRELIQ_GENERICO_EXT_BAD';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE WTMP_SALDOS_BAD';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Error_Cargue_Linea CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Listas_R CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Preliq_UARIV CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Preliq_MFEA CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Preliq_OTROS CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SALDOS CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Procesa_Listas_R CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Procesa_preliq_generico CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Resumen_Cargue CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Tipo_Archivo CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE PARAMETROS_SIBO CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE CRUCE_RECHAZO_RESUMEN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE ERR$_LST_RESTRICTIVAS20170103';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE ERR$_PRELIQ_GENERICO20170103';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE CONDICIONALES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE MOTIVO_RECHAZO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE AUTENTICACION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TIPO_DOCUMENTO CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE REL_PRELIQ_TIPOPAGO CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
