-- Generado por Oracle SQL Developer Data Modeler 4.1.3.901
--   en:        2016-12-09 09:14:28 COT
--   sitio:     Oracle Database 11g
--   tipo:      Oracle Database 11g
--   Diseñó     Alfonso Pimienta
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.PRELIQ_GENERICO' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.LST_RESTRICTIVAS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.WTMP_LST_RESTRICTIVAS_EXT_BAD' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.WTMP_PRELIQ_GENERICO_EXT_BAD';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.WTMP_SALDOS_BAD';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Error_Cargue_Linea CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Listas_R CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Preliq_UARIV CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Preliq_MFEA CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Preliq_OTROS CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.SALDOS CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Procesa_Listas_R CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Procesa_preliq_generico CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Resumen_Cargue CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Tipo_Archivo CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.PARAMETROS_SIBO CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.CRUCE_RECHAZO_RESUMEN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.ERR$_LST_RESTRICTIVAS20170103';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.ERR$_PRELIQ_GENERICO20170103';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.CONDICIONALES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.MOTIVO_RECHAZO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.AUTENTICACION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.TIPO_DOCUMENTO CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.REL_PRELIQ_TIPOPAGO CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;


-----------CREATE
/
BEGIN
EXECUTE IMMEDIATE 'CREATE TABLE STG_SIBO.WTMP_LST_RESTRICTIVAS_EXT_BAD(LINEA  VARCHAR2(1000), DESCRIPCION VARCHAR2(100))';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'CREATE TABLE STG_SIBO.WTMP_PRELIQ_GENERICO_EXT_BAD( LINEA VARCHAR2(1000), DESCRIPCION VARCHAR2(100))';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'CREATE TABLE STG_SIBO.WTMP_SALDOS_EXT_BAD( LINEA VARCHAR2(1000), DESCRIPCION  VARCHAR2(100))';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
/*
CREATE TABLE ERR$_LST_RESTRICTIVAS20170103
  (
    TIPOIDENTIFICACION     VARCHAR2(10),
    IDENTIFICACION         NUMBER(16),
    IDENTIFICADORNODESEADO VARCHAR2(3),
    DESCRIPCION            VARCHAR2(100)
  );

CREATE TABLE ERR$_PRELIQ_GENERICO20170103
  (
    IDULTIMAPRELIQUIDACION INTEGER NOT NULL ,
    IDCARGUE               INTEGER NOT NULL ,
    CODMUNICIPIO           NUMBER (5) NOT NULL ,
    DEPARTAMENTO           VARCHAR2 (60 BYTE) ,
    MUNICIPIO              VARCHAR2 (50 BYTE) ,
    CODBENEFICIARIO        NUMBER (7) NOT NULL ,
    NOMBRE1                VARCHAR2 (20 BYTE) ,
    NOMBRE2                VARCHAR2 (20 BYTE) ,
    APELLIDO1              VARCHAR2 (20 BYTE) ,
    APELLIDO2              VARCHAR2 (20 BYTE) ,
    TIPOID                 VARCHAR2 (2 BYTE) ,
    DOCUMENTO              NUMBER (12) NOT NULL ,
    TELEFONO               NUMBER (10) ,
    CELULAR                NUMBER (10) ,
    DIRECCION              VARCHAR2 (50 BYTE) ,
    CORREOELECTRONICO      VARCHAR2 (50 BYTE) ,
    FECHANACIMIENTO        DATE ,
    FECHAEXPEDICION        DATE ,
    SEXO                   VARCHAR2 (1 BYTE) ,
    VALORTOTAL             NUMBER (15)
  );
*/

CREATE TABLE Error_Cargue_Linea
  (
    IDERRORLINEACARGUE INTEGER NOT NULL ,
    IDCARGUE           INTEGER ,
    LINEA              VARCHAR2 (4000 BYTE) NOT NULL ,
    DESCRIPCIONERROR   VARCHAR2 (100 BYTE)
  );
ALTER TABLE Error_Cargue_Linea ADD CONSTRAINT Error_Cargue_Linea_PK PRIMARY KEY ( IDERRORLINEACARGUE ) ;

CREATE TABLE Listas_R
  (
    IDLISTASR              INTEGER NOT NULL ,
    IDCARGUE               INTEGER NOT NULL ,
    TIPOIDENTIFICACION     VARCHAR2 (10 BYTE) NOT NULL ,
    IDENTIFICACION         NUMBER (16) NOT NULL ,
    IDENTIFICADORNODESEADO VARCHAR2 (3 BYTE)
  );
ALTER TABLE Listas_R ADD CONSTRAINT Listas_R_PK PRIMARY KEY ( IDLISTASR ) ;


CREATE TABLE PRELIQ_UARIV
   (	
  IDPRELIQ NUMBER(*,0) NOT NULL ENABLE, 
	IDCARGUE NUMBER(*,0) NOT NULL ENABLE, 
	CODMUNICIPIO NUMBER(5,0) NOT NULL ENABLE, 
	DEPARTAMENTO VARCHAR2(60 BYTE), 
	MUNICIPIO VARCHAR2(50 BYTE), 
	CODBENEFICIARIO NUMBER(7,0) NOT NULL ENABLE, 
	NOMBRE1 VARCHAR2(20 BYTE), 
	NOMBRE2 VARCHAR2(20 BYTE), 
	APELLIDO1 VARCHAR2(20 BYTE), 
	APELLIDO2 VARCHAR2(20 BYTE), 
	TIPOID VARCHAR2(2 BYTE), 
	DOCUMENTO NUMBER(12,0) NOT NULL ENABLE, 
	TELEFONO NUMBER(10,0), 
	CELULAR NUMBER(10,0), 
	DIRECCION VARCHAR2(50 BYTE), 
	CORREOELECTRONICO VARCHAR2(50 BYTE), 
	FECHANACIMIENTO DATE, 
	FECHAEXPEDICION DATE, 
	SEXO VARCHAR2(1 BYTE), 
	VALORTOTAL NUMBER(15,0)
  );
ALTER TABLE PRELIQ_UARIV ADD CONSTRAINT Preliquidacion_Victimas_PK PRIMARY KEY ( IDPRELIQ ) ;

CREATE TABLE Preliq_MFEA
  (
    IDPRELIQ               INTEGER NOT NULL ,
    IDCARGUE               INTEGER NOT NULL ,
    CODMUNICIPIO           NUMBER (5) NOT NULL ,
    DEPARTAMENTO           VARCHAR2 (60 BYTE) ,
    MUNICIPIO              VARCHAR2 (50 BYTE) ,
    CODBENEFICIARIO        NUMBER (7) NOT NULL ,
    NOMBRE1                VARCHAR2 (20 BYTE) ,
    NOMBRE2                VARCHAR2 (20 BYTE) ,
    APELLIDO1              VARCHAR2 (20 BYTE) ,
    APELLIDO2              VARCHAR2 (20 BYTE) ,
    TIPOID                 VARCHAR2 (2 BYTE) ,
    DOCUMENTO              NUMBER (12) NOT NULL ,
    TELEFONO               NUMBER (10) ,
    CELULAR                NUMBER (10) ,
    DIRECCION              VARCHAR2 (50 BYTE) ,
    CORREOELECTRONICO      VARCHAR2 (50 BYTE) ,
    FECHANACIMIENTO        DATE ,
    FECHAEXPEDICION        DATE ,
    SEXO                   VARCHAR2 (1 BYTE) ,
    VALORTOTAL             NUMBER (15)
  );
ALTER TABLE Preliq_MFEA ADD CONSTRAINT Preli_MFEA_PK PRIMARY KEY (IDPRELIQ) ;

CREATE TABLE Preliq_OTROS
  (
    IDPRELIQ               INTEGER NOT NULL ,
    IDCARGUE               INTEGER NOT NULL ,
    CODMUNICIPIO           NUMBER (5) NOT NULL ,
    DEPARTAMENTO           VARCHAR2 (60 BYTE) ,
    MUNICIPIO              VARCHAR2 (50 BYTE) ,
    CODBENEFICIARIO        NUMBER (7) NOT NULL ,
    NOMBRE1                VARCHAR2 (20 BYTE) ,
    NOMBRE2                VARCHAR2 (20 BYTE) ,
    APELLIDO1              VARCHAR2 (20 BYTE) ,
    APELLIDO2              VARCHAR2 (20 BYTE) ,
    TIPOID                 VARCHAR2 (2 BYTE) ,
    DOCUMENTO              NUMBER (12) NOT NULL ,
    TELEFONO               NUMBER (10) ,
    CELULAR                NUMBER (10) ,
    DIRECCION              VARCHAR2 (50 BYTE) ,
    CORREOELECTRONICO      VARCHAR2 (50 BYTE) ,
    FECHANACIMIENTO        DATE ,
    FECHAEXPEDICION        DATE ,
    SEXO                   VARCHAR2 (1 BYTE) ,
    VALORTOTAL             NUMBER (15)
  );
ALTER TABLE Preliq_OTROS ADD CONSTRAINT Preli_OTROS_PK PRIMARY KEY ( IDPRELIQ ) ;

CREATE TABLE SALDOS
   (	
  IDSALDO NUMBER NOT NULL ENABLE, 
	IDCARGUE NUMBER NOT NULL ENABLE, 
	BIN NUMBER(9,0) NOT NULL ENABLE, 
	NITEMPRESA NUMBER(15,0) NOT NULL ENABLE, 
	IDDAVIPLATA NUMBER(19,0) NOT NULL ENABLE, 
	MIEMBRO NUMBER(3,0) NOT NULL ENABLE, 
	NOMBRETITULAR VARCHAR2(27 BYTE) NOT NULL ENABLE, 
	SALDODISPONIBLE NUMBER(17,2) NOT NULL ENABLE, 
	ESTADOTARJETA VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	DESCRIPCIONESTADO VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	SUBTIPO VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	TIPOID VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	DOCUMENTO NUMBER(15,0) NOT NULL ENABLE, 
	ORIGENCREACION VARCHAR2(1 BYTE), 
	CONSTRAINT SALDOS_PK PRIMARY KEY (IDSALDO),
  CONSTRAINT "SALDOS_UK" UNIQUE ("IDCARGUE", "TIPOID", "DOCUMENTO")
  );
/*
CREATE TABLE Procesa_Listas_R
  (
    IDLISTASR              INTEGER NOT NULL ,
    TIPOIDENTIFICACION     VARCHAR2 (10 BYTE) ,
    IDENTIFICACION         NUMBER (16) ,
    IDENTIFICADORNODESEADO VARCHAR2 (3 BYTE)
  );
ALTER TABLE Procesa_Listas_R ADD CONSTRAINT Procesa_Listas_R_PK PRIMARY KEY ( IDLISTASR ) ;

CREATE TABLE Procesa_preliq_generico
  (
    IDTRANSPRELIQUIDACION INTEGER NOT NULL ,
    CODMUNICIPIO          NUMBER (5) ,
    DEPARTAMENTO          VARCHAR2 (60 BYTE) ,
    MUNICIPIO             VARCHAR2 (50 BYTE) ,
    CODBENEFICIARIO       NUMBER (7) ,
    NOMBRE1               VARCHAR2 (20 BYTE) ,
    NOMBRE2               VARCHAR2 (20 BYTE) ,
    APELLIDO1             VARCHAR2 (20 BYTE) ,
    APELLIDO2             VARCHAR2 (20 BYTE) ,
    TIPOID                VARCHAR2 (2 BYTE) ,
    DOCUMENTO             NUMBER (12) ,
    TELEFONO              NUMBER (10) ,
    CELULAR               NUMBER (10) ,
    DIRECCION             VARCHAR2 (50 BYTE) ,
    CORREOELECTRONICO     VARCHAR2 (50 BYTE) ,
    FECHANACIMIENTO       DATE ,
    FECHAEXPEDICION       DATE ,
    SEXO                  VARCHAR2 (1 BYTE) ,
    VALORTOTAL            NUMBER (15)
  );
ALTER TABLE Procesa_preliq_generico ADD CONSTRAINT Procesa_Victimas_PK PRIMARY KEY ( IDTRANSPRELIQUIDACION ) ;
*/

CREATE TABLE Resumen_Cargue
  (
    IDCARGUE             INTEGER NOT NULL ,
    IDTIPOARCHIVO        INTEGER NOT NULL ,
    FECHA                DATE ,
    HORA                 VARCHAR2 (8 BYTE) NOT NULL ,
    NUMEROCARGUE         INTEGER NOT NULL ,
    TOTALREGISTROS       INTEGER NOT NULL ,
    TOTALCARGADOS        INTEGER NOT NULL ,
    TOTALERRADOS         INTEGER NOT NULL ,
    NOMBREARCHIVOCARGADO VARCHAR2 (40 BYTE)
  );
ALTER TABLE Resumen_Cargue ADD CONSTRAINT Resumen_Cargue_PK PRIMARY KEY (IDCARGUE) ;

CREATE TABLE Tipo_Archivo
  (
    IDTIPOARCHIVO     INTEGER NOT NULL ,
    NOMBRETIPOARCHIVO VARCHAR2 (60 BYTE) NOT NULL ,
    SEPARADOR         VARCHAR2 (1 CHAR) NOT NULL ,
    TABLAINSERCION    VARCHAR2 (30 BYTE) NOT NULL,
    IDENTIFICADOR     CHAR(1 BYTE) DEFAULT 1 NOT NULL ENABLE,
    SECUENCIA         VARCHAR2(40 BYTE)
  );
ALTER TABLE TIPO_ARCHIVO ADD CONSTRAINT TIPO_ARCHIVO_PK PRIMARY KEY (IDTIPOARCHIVO) ;

CREATE TABLE PARAMETROS_SIBO
  (
    ID_PARAMETRO      NUMBER NOT NULL,
    NOMBRE_PARAMETRO  VARCHAR2(60 BYTE) NOT NULL ,
    VALOR_PARAMETRO   VARCHAR2(2000 BYTE) NOT NULL ,
    DESCRIPCION_PARAM VARCHAR2(500 BYTE)
  );
ALTER TABLE PARAMETROS_SIBO ADD CONSTRAINT PARAMETROS_SIBO_PK PRIMARY KEY (ID_PARAMETRO);
ALTER TABLE PARAMETROS_SIBO ADD CONSTRAINT PARAMETROS_SIBO_UK UNIQUE (NOMBRE_PARAMETRO);

CREATE TABLE PRELIQ_GENERICO
  (
    ID                NUMBER(*, 0) NOT NULL PRIMARY KEY ,
    CODMUNICIPIO      NUMBER(5, 0) NOT NULL ,
    DEPARTAMENTO      VARCHAR2(60 BYTE) ,
    MUNICIPIO         VARCHAR2(50 BYTE) ,
    CODBENEFICIARIO   NUMBER(7, 0) NOT NULL ,
    NOMBRE1           VARCHAR2(20 BYTE) ,
    NOMBRE2           VARCHAR2(20 BYTE) ,
    APELLIDO1         VARCHAR2(20 BYTE) ,
    APELLIDO2         VARCHAR2(20 BYTE) ,
    TIPOID            VARCHAR2(2 BYTE) ,
    DOCUMENTO         NUMBER(12, 0) NOT NULL ,
    TELEFONO          NUMBER(10, 0) ,
    CELULAR           NUMBER(10, 0) ,
    DIRECCION         VARCHAR2(50 BYTE) ,
    CORREOELECTRONICO VARCHAR2(50 BYTE) ,
    FECHANACIMIENTO   DATE ,
    FECHAEXPEDICION   DATE ,
    SEXO              VARCHAR2(1 BYTE) ,
    VALORTOTAL        NUMBER(15, 0)
  );
  
CREATE TABLE LST_RESTRICTIVAS 
(
  IDLISTASR NUMBER(*, 0) NOT NULL 
, TIPOIDENTIFICACION VARCHAR2(10 BYTE) 
, IDENTIFICACION NUMBER(16, 0) 
, IDENTIFICADORNODESEADO VARCHAR2(3 BYTE) 
, CONSTRAINT PROCESA_LISTAS_R_PK PRIMARY KEY ( IDLISTASR )
);

CREATE TABLE AUTENTICACION 
   (	
  "USERNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(200 BYTE), 
	 CONSTRAINT "AUTENTICACION_PK" PRIMARY KEY ("USERNAME")
   );

CREATE TABLE MOTIVO_RECHAZO
   (	
  IDRECHAZO NUMBER PRIMARY KEY, 
	DESCRIPCION VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	ESTADORECHAZO NUMBER(1,0) DEFAULT 2 NOT NULL ENABLE, 
  CONSTRAINT ESTADORECHAZO_CK CHECK (ESTADORECHAZO IN(2, 3)) ENABLE
  );

CREATE TABLE CRUCE_RECHAZO_RESUMEN
  (
    IDRECHAZO NUMBER,
    IDCARGUE  NUMBER,
    CONSTRAINT CRUCE_RECHAZO_PK PRIMARY KEY (IDRECHAZO, IDCARGUE),
    CONSTRAINT CRUCE_RECHAZO_FK FOREIGN KEY (IDCARGUE) REFERENCES RESUMEN_CARGUE (IDCARGUE) ON DELETE CASCADE ENABLE
  );

CREATE TABLE CONDICIONALES 
(
  IDCONDICIONAL NUMBER NOT NULL PRIMARY KEY
, IDCARGUE NUMBER NOT NULL 
, TIPOID VARCHAR2(2 BYTE) NOT NULL
, DOCUMENTO NUMBER(12) NOT NULL
, TIPOPAGO NUMBER(1) NOT NULL
); 

CREATE TABLE TIPO_DOCUMENTO 
(
  TIPOID VARCHAR2(2 BYTE) NOT NULL 
, DESCRIPCION VARCHAR2(50 BYTE) NOT NULL 
, CONSTRAINT TIPO_DOCUMENTO_PK PRIMARY KEY ( TIPOID )
);
ALTER TABLE TIPO_DOCUMENTO ADD CONSTRAINT TIPO_DOCUMENTO_UK UNIQUE ( DESCRIPCION );

CREATE TABLE REL_PRELIQ_TIPOPAGO 
  (
  IDRELPRELIQ NUMBER, 
	IDCARGUE NUMBER NOT NULL ENABLE, 
	IDPRELIQ NUMBER(38,0) NOT NULL ENABLE, 
	IDTIPOPAGO NUMBER(1,0) NOT NULL ENABLE, 
	 CONSTRAINT REL_PRELIQ_CARGUE_PK PRIMARY KEY ( IDRELPRELIQ )
);


ALTER TABLE CONDICIONALES ADD CONSTRAINT RESUMEN_CARGUE_CONDICIONAL_FK FOREIGN KEY (IDCARGUE) REFERENCES RESUMEN_CARGUE (IDCARGUE) ON DELETE CASCADE ENABLE;
ALTER TABLE CONDICIONALES ADD CONSTRAINT TIPO_DOCUMENTO_CONDICIONAL_FK FOREIGN KEY (TIPOID)   REFERENCES TIPO_DOCUMENTO (TIPOID)   ON DELETE CASCADE ENABLE;
ALTER TABLE CONDICIONALES ADD CONSTRAINT CONDICIONALES_UK UNIQUE (TIPOID,DOCUMENTO,IDCARGUE);
ALTER TABLE CONDICIONALES ADD CONSTRAINT CONDICIONALES_CK CHECK  (TIPOPAGO IN(1,2,3)) ENABLE;
  
ALTER TABLE Error_Cargue_Linea ADD CONSTRAINT Error_Cargue_Linea_Resumen_FK FOREIGN KEY ( IDCARGUE ) REFERENCES Resumen_Cargue ( IDCARGUE ) ON DELETE CASCADE ;
ALTER TABLE Listas_R ADD CONSTRAINT Listas_R_Resumen_FK FOREIGN KEY ( IDCARGUE ) REFERENCES Resumen_Cargue ( IDCARGUE ) ON DELETE CASCADE ;
ALTER TABLE PRELIQ_UARIV ADD CONSTRAINT PRELIQ_AURIV_Resumen_FK FOREIGN KEY ( IDCARGUE ) REFERENCES Resumen_Cargue ( IDCARGUE ) ON DELETE CASCADE ;
ALTER TABLE PRELIQ_MFEA ADD CONSTRAINT PRELIQ_MFEA_Resumen_FK FOREIGN KEY ( IDCARGUE ) REFERENCES Resumen_Cargue ( IDCARGUE ) ON DELETE CASCADE ;
ALTER TABLE PRELIQ_OTROS ADD CONSTRAINT PRELIQ_OTROS_Resumen_FK FOREIGN KEY ( IDCARGUE ) REFERENCES Resumen_Cargue ( IDCARGUE ) ON DELETE CASCADE ;
ALTER TABLE Resumen_Cargue ADD CONSTRAINT Resumen_Tipo_Archivo_FK FOREIGN KEY ( IDTIPOARCHIVO ) REFERENCES Tipo_Archivo ( IDTIPOARCHIVO ) ON DELETE CASCADE ;
