
ALTER TABLE REL_PRELIQ_TIPOPAGO DROP CONSTRAINT FK_REL_PRELIQ_ESTADO_PAGO;

CREATE TABLE "STG_SIBO"."ESTADO_PROCESO_PAGO" 
   (	"ID" NUMBER, 
	"DESCRIPCION" VARCHAR2(100 BYTE)
   );
   
  CREATE UNIQUE INDEX "STG_SIBO"."ESTADO_PROCESO_PAGO_PK" ON "STG_SIBO"."ESTADO_PROCESO_PAGO" ("ID");

  ALTER TABLE "STG_SIBO"."ESTADO_PROCESO_PAGO" ADD CONSTRAINT "ESTADO_PROCESO_PAGO_PK" PRIMARY KEY ("ID");
   
ALTER TABLE REL_PRELIQ_TIPOPAGO ADD CONSTRAINT FK_REL_PRELIQ_ESTADO_PROCESO_PAGO  
FOREIGN KEY ( ESTADO_PAGO ) REFERENCES ESTADO_PROCESO_PAGO ( ID );