INSERT INTO STG_SIBO.TIPO_ARCHIVO (IDTIPOARCHIVO,NOMBRETIPOARCHIVO,SEPARADOR,TABLAINSERCION,IDENTIFICADOR,SECUENCIA) VALUES (7,'REDEBAN',';','REDEBAN_ENC_RESPUESTA','7','SEQ_REDEBAN');

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.REDEBAN_ENC_RESPUESTA' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.REDEBAN_DET_RESPUESTA' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
/*
****ELIMINAR LLAVES FORANEAS ANTES DE CREAR LA TABLA. */

--ALTER TABLE STG_SIBO.REDEBAN_DET_RESPUESTA drop CONSTRAINT REDB_DET_RESP_IDENCABEZADO_FK;

--ALTER TABLE STG_SIBO.REDEBAN_ENC_RESPUESTA drop CONSTRAINT REDB_ENC_PK;

CREATE TABLE STG_SIBO.REDEBAN_ENC_RESPUESTA
  (
  ID              NUMBER(*,0) NOT NULL ENABLE, 
  IDCARGUE        NUMBER(*,0) NOT NULL ENABLE, 
  NIT             NUMBER(15,0),
  FECHAENVIO      NUMBER(8,0),
  CONSECUTIVO     NUMBER(5,0),
  NUMEROREGISTROS NUMBER(6,0),
  DISPONIBLE      VARCHAR2(34 BYTE),
  MONTO           NUMBER(19,0),
  MONTOINVERTIDO  NUMBER(19,0),
  DISPONIBLEBLANCOS VARCHAR2(19 BYTE),
  SUBTIPO           VARCHAR2(3 BYTE),
  INDICADORTRAILER  VARCHAR2(1 BYTE),
  CODIGOERROR       VARCHAR2(3 BYTE)
  );

ALTER TABLE STG_SIBO.REDEBAN_ENC_RESPUESTA ADD CONSTRAINT REDB_ENC_PK PRIMARY KEY (ID) ;

CREATE TABLE STG_SIBO.REDEBAN_DET_RESPUESTA
  (
  ID                  NUMBER(*,0) NOT NULL ENABLE, 
  IDCARGUE            NUMBER(*,0) NOT NULL ENABLE, 
  NIT                 NUMBER(15,0),
  FECHAENVIO          NUMBER(8,0),
  CONSECUTIVO         NUMBER(5,0),
  TIPOIDENTIFICACION  VARCHAR2(2 BYTE),
  NUMEROIDENTIFICACION NUMBER(15,0),
  NUMEROTARJETA       VARCHAR2(19 BYTE),
  NUMEROCUENTA        VARCHAR2(19 BYTE),
  TIPONOVEDAD         VARCHAR2(1 BYTE),
  VALORNOVEDAD        NUMBER(17,0),
  INDICADORMSG        VARCHAR2(1 BYTE),
  DISPONIBLE          VARCHAR2(27 BYTE),
  CODIGOERROR         VARCHAR2(3 BYTE),
  IDENCABEZADO      NUMBER(*,0)
  );
  
ALTER TABLE STG_SIBO.REDEBAN_DET_RESPUESTA ADD CONSTRAINT REDB_DET_PK PRIMARY KEY (ID) ;

ALTER TABLE STG_SIBO.REDEBAN_DET_RESPUESTA ADD CONSTRAINT REDB_DET_RESP_IDENCABEZADO_FK  
FOREIGN KEY ( IDENCABEZADO ) REFERENCES STG_SIBO.REDEBAN_ENC_RESPUESTA ( ID );


/*SEQUENCE*/
CREATE SEQUENCE SEQ_REDEBAN_ENC_RESPUESTA INCREMENT BY 1 START WITH 1 MINVALUE 1 ORDER;
CREATE SEQUENCE SEQ_REDEBAN_DET_RESPUESTA INCREMENT BY 1 START WITH 1 MINVALUE 1 ORDER;

