CREATE TABLE STG_SIBO.MOTIVOS_RECHAZOS_PAGO 
(
  ID_MOTIVO_RECHAZO_PAGO INTEGER NOT NULL PRIMARY KEY
, CAUSALES_RECHAZO_PAGO VARCHAR2(200) NOT NULL 
);

COMMENT ON COLUMN MOTIVO_RECHAZO_PAGO.ID_MOTIVO_RECHAZO_PAGO IS 'Llave primaria';
COMMENT ON COLUMN MOTIVO_RECHAZO_PAGO.CAUSALES_RECHAZO_PAGO IS 'Desccripción de la causal motivo rechazo de pago';


ALTER TABLE PROCESO_PAGO ADD (CONSECUTIVO_PROCESO_PAGO VARCHAR2(25)) ;
ALTER TABLE PROCESO_PAGO ADD CONSTRAINT UK_PROCESO_PAGO_CONSECUTIVO UNIQUE (CONSECUTIVO_PROCESO_PAGO);

ALTER TABLE DISPERSION_DAVIPLATA 
ADD (CONSECUTIVO_PROCESO_PAGO VARCHAR2(25) );

CREATE INDEX "STG_SIBO"."DISPERSION_DAVIPLATA_INDX3" ON "STG_SIBO"."DISPERSION_DAVIPLATA" ("IDCARGUE", "CONSECUTIVO_PROCESO_PAGO") TABLESPACE SIBO_INDICES;

   
ALTER TABLE STG_SIBO.REL_PRELIQ_TIPOPAGO ADD(
	ESTADO_PAGO 				      INTEGER,
	ID_DAVIPLATA 				      NUMBER(38,0),
	VALOR_TOTAL					      NUMBER(17,2),
	ID_MOTIVO_RECHAZO_PAGO 	  		  INTEGER,
	FECHA_DISPERSION 			    DATE,
	CONSECUTIVO_PROCESO_PAGO	VARCHAR2(25),
	CONSTRAINT FK_REL_PRELIQ_ESTADO_PAGO    	FOREIGN KEY (ESTADO_PAGO)                REFERENCES STG_SIBO.ESTADO_PAGO(ID_EST_PAGO),
	CONSTRAINT FK_REL_PRELIQ_MOTIVO_RECH_PAGO   FOREIGN KEY (ID_MOTIVO_RECHAZO_PAGO)   REFERENCES STG_SIBO.MOTIVO_RECHAZO_PAGO(ID_MOTIVO_RECHAZO_PAGO)
--	CONSTRAINT FK_REL_PRELIQ_PROCESO_PAGO    	FOREIGN KEY (CONSECUTIVO_PROCESO_PAGO)   REFERENCES STG_SIBO.PROCESO_PAGO(CONSECUTIVO)
);

ALTER TABLE STG_SIBO.RESUMEN_CARGUE ADD (  
  FECHA_INICIO_PROCESO      DATE,
  FECHA_FIN_PROCESO         DATE,
  ID_CONVENIO               NUMBER(8)
);