DROP TABLE STG_SIBO.MOTIVOS_RECHAZOS_PAGO;
ALTER TABLE STG_SIBO.PROCESO_PAGO DROP COLUMN CONSECUTIVO CASCADE CONSTRAINTS;
ALTER TABLE STG_SIBO.REL_PRELIQ_TIPOPAGO DROP COLUMN ESTADO_PAGO CASCADE CONSTRAINTS;
ALTER TABLE STG_SIBO.REL_PRELIQ_TIPOPAGO DROP COLUMN ID_DAVIPLATA CASCADE CONSTRAINTS;
ALTER TABLE STG_SIBO.REL_PRELIQ_TIPOPAGO DROP COLUMN VALOR_TOTAL CASCADE CONSTRAINTS;
ALTER TABLE STG_SIBO.REL_PRELIQ_TIPOPAGO DROP COLUMN ID_MOTIVO_RECHAZO_PAGO CASCADE CONSTRAINTS;
ALTER TABLE STG_SIBO.REL_PRELIQ_TIPOPAGO DROP COLUMN FECHA_DISPERSION CASCADE CONSTRAINTS;
ALTER TABLE STG_SIBO.REL_PRELIQ_TIPOPAGO DROP COLUMN FECHA_INICIO_PROCESO CASCADE CONSTRAINTS;
ALTER TABLE STG_SIBO.REL_PRELIQ_TIPOPAGO DROP COLUMN FECHA_FIN_PROCESO CASCADE CONSTRAINTS;
ALTER TABLE STG_SIBO.REL_PRELIQ_TIPOPAGO DROP COLUMN CONSECUTIVO_PROCESO_PAGO CASCADE CONSTRAINTS;


