-------------------------------------------------------------------------------------------
--  Borrado de tablass, Procedimientos almacenados, Vistas y Secuencas para CO_532
-------------------------------------------------------------------------------------------

DROP TABLE CO532_ASIGNACION CASCADE CONSTRAINTS;
DROP TABLE CO532_ATRI_CALIF CASCADE CONSTRAINTS;
DROP TABLE CO532_BITA_SINI CASCADE CONSTRAINTS;
DROP TABLE CO532_BITA_SIST CASCADE CONSTRAINTS;
DROP TABLE CO532_CALIF_ABOG CASCADE CONSTRAINTS;
DROP TABLE CO532_COMISION CASCADE CONSTRAINTS;
DROP TABLE CO532_COMIS_DETA CASCADE CONSTRAINTS;
DROP TABLE CO532_DET_HIST_DISTR CASCADE CONSTRAINTS;
DROP TABLE CO532_DET_LLAV_CUMP CASCADE CONSTRAINTS;
DROP TABLE CO532_EXCL_CAS CASCADE CONSTRAINTS;
DROP TABLE CO532_EXCL_EST_FEC CASCADE CONSTRAINTS;
DROP TABLE CO532_EXCL_FEC CASCADE CONSTRAINTS;
DROP TABLE CO532_EXCL_MONT CASCADE CONSTRAINTS;
DROP TABLE CO532_EXCL_POL CASCADE CONSTRAINTS;
DROP TABLE CO532_GESTOR CASCADE CONSTRAINTS;
DROP TABLE CO532_GEST_LOC CASCADE CONSTRAINTS;
DROP TABLE CO532_HIST_DISTR CASCADE CONSTRAINTS;
DROP TABLE CO532_INACT_GEST CASCADE CONSTRAINTS;
DROP TABLE CO532_LIQUIDADOR CASCADE CONSTRAINTS;
DROP TABLE CO532_LLAV_CUMPL CASCADE CONSTRAINTS;
DROP TABLE CO532_LOCALIZACION CASCADE CONSTRAINTS;
DROP TABLE CO532_META_GLOB CASCADE CONSTRAINTS;
DROP TABLE CO532_META_GLOB_DET CASCADE CONSTRAINTS;
DROP TABLE CO532_MOT_EXCL CASCADE CONSTRAINTS;
DROP TABLE CO532_NOTIFICACION CASCADE CONSTRAINTS;
DROP TABLE CO532_NOT_TIP_GEST CASCADE CONSTRAINTS;
DROP TABLE CO532_PAGO CASCADE CONSTRAINTS;
DROP TABLE CO532_PAR_CAL_ABOG CASCADE CONSTRAINTS;
DROP TABLE CO532_PERIODO CASCADE CONSTRAINTS;
DROP TABLE CO532_POLIZA CASCADE CONSTRAINTS;
DROP TABLE CO532_RANG_AGRU CASCADE CONSTRAINTS;
DROP TABLE CO532_RANG_LIQU CASCADE CONSTRAINTS;
DROP TABLE CO532_REG_DIST CASCADE CONSTRAINTS;
DROP TABLE CO532_RE_CAL_MET_GLO CASCADE CONSTRAINTS;
DROP TABLE CO532_SINIESTRO CASCADE CONSTRAINTS;
DROP TABLE CO532_TIP_DISTR CASCADE CONSTRAINTS;
DROP TABLE CO532_VARIABLE CASCADE CONSTRAINTS;
DROP TABLE CO532_VAR_REGL CASCADE CONSTRAINTS;

DROP SEQUENCE CO532_SEC_BITA_SIST;
DROP SEQUENCE CO532_SEC_GEST_LOC;
DROP SEQUENCE CO532_SEC_INACT_GEST;
DROP SEQUENCE CO532_SEC_TIP_DISTR;
DROP SEQUENCE CO532_SEC_RANG_AGRU;
DROP SEQUENCE CO532_SEC_EXCL_CAS;
DROP SEQUENCE CO532_SEC_EXCL_EST_FEC;
DROP SEQUENCE CO532_SEC_EXCL_FEC;
DROP SEQUENCE CO532_SEC_EXCL_MONT;
DROP SEQUENCE CO532_SEC_EXCL_POL;
DROP SEQUENCE CO532_SEC_GESTOR;
DROP SEQUENCE CO532_SEC_SINIESTRO;
DROP SEQUENCE CO532_SEC_DET_HIST_DIST;
DROP SEQUENCE  co532_hist_distr;

COMMIT;
