--Secuencia rango agrupacion
CREATE SEQUENCE co532_sec_rang_agru START WITH 1 MINVALUE 1 MAXVALUE 99999 NOCACHE ORDER;

--Secuencia exlcusion por caso
CREATE SEQUENCE co532_sec_excl_cas START WITH 1 MINVALUE 1 MAXVALUE 99999 NOCACHE ORDER;

--Secuencia exlcusion por estado y fecha
CREATE SEQUENCE co532_sec_excl_est_fec START WITH 1 MINVALUE 1 MAXVALUE 99999 NOCACHE ORDER;

--Secuencia exlcusion por fecha
CREATE SEQUENCE co532_sec_excl_fec START WITH 1 MINVALUE 1 MAXVALUE 99999 NOCACHE ORDER;

--Secuencia exlcusion por monto
CREATE SEQUENCE co532_sec_excl_mont START WITH 1 MINVALUE 1 MAXVALUE 99999 NOCACHE ORDER;

--Secuencia exlcusion por poliza
CREATE SEQUENCE co532_sec_excl_pol START WITH 1 MINVALUE 1 MAXVALUE 99999 NOCACHE ORDER;

--Secuencia gestor
CREATE SEQUENCE co532_sec_gestor START WITH 1 MINVALUE 1 MAXVALUE 99999 NOCACHE ORDER;

--Secuencia siniestro
CREATE SEQUENCE co532_sec_siniestro START WITH 1 MINVALUE 1 MAXVALUE 99999 NOCACHE ORDER;

--Secuencia hISTORICO DISTRIBUCION
CREATE SEQUENCE co532_hist_distr START WITH 1 MINVALUE 1 MAXVALUE 99999 NOCACHE ORDER;


--Secuencia detalle historico distribucion
CREATE SEQUENCE co532_sec_det_hist_dist START WITH 1 MINVALUE 1 MAXVALUE 99999999999 NOCACHE ORDER;