set define off;
@"Packages\PKG_OPERACION.pks"
@"Packages\PKG_OPERACION.pkb"
@"Packages\PKG_NOVEDADES_WEB_JAVA.pks"
@"Packages\PKG_NOVEDADES_WEB_JAVA.pkb"
@"Packages\OBJETARSUBSANAR.pks"
@"Packages\OBJETARSUBSANAR.pkb"
@"Packages\PKG_CONSULTA_INDEMNIZACION.pks"
@"Packages\PKG_CONSULTA_INDEMNIZACION.pkb"
@"Packages\PKG_DETALLE_OPERACION.pks"
@"Packages\PKG_DETALLE_OPERACION.pkb"
@"Packages\PKG_INTERFACES_CONSULTAS.pks"
@"Packages\PKG_INTERFACES_CONSULTAS.pkb"
@"Packages\PKG_INTERFACES_OPERACIONES.pks"
@"Packages\PKG_INTERFACES_OPERACIONES.pkb"
@"Packages\PKG_INTERFACES_SINIESTROS.pks"
@"Packages\PKG_INTERFACES_SINIESTROS.pkb"
@"Packages\PKG_OBJETAR_SUBSANAR.pks"
@"Packages\PKG_OBJETAR_SUBSANAR.pkb"
@"Packages\PK_LISTADOS_CIERRE.pks"
@"Packages\PK_LISTADOS_CIERRE.pkb"
ALTER PACKAGE admsisa.PKG_OPERACION COMPILE BODY;
ALTER PACKAGE admsisa.PKG_NOVEDADES_WEB_JAVA COMPILE BODY;
ALTER PACKAGE admsisa.OBJETARSUBSANAR COMPILE BODY;
ALTER PACKAGE admsisa.PKG_CONSULTA_INDEMNIZACION COMPILE BODY;
ALTER PACKAGE admsisa.PKG_DETALLE_OPERACION COMPILE BODY;
ALTER PACKAGE admsisa.PKG_INTERFACES_CONSULTAS COMPILE BODY;
ALTER PACKAGE admsisa.PKG_INTERFACES_OPERACIONES COMPILE BODY;
ALTER PACKAGE admsisa.PKG_INTERFACES_SINIESTROS COMPILE BODY;
ALTER PACKAGE admsisa.PKG_OBJETAR_SUBSANAR COMPILE BODY;
ALTER PACKAGE admsisa.PK_LISTADOS_CIERRE COMPILE BODY;
exit