--------------------------------------------------------
--  Ref Constraints for Table AUTORIZACION_INDEMNIZACION
--------------------------------------------------------
  ALTER TABLE "AUTORIZACION_INDEMNIZACION" ADD CONSTRAINT "AUTO_IND_DANIO_FALT_PEND_FK" FOREIGN KEY ("DAN_FALT_PEND_FEC_REP", "DAN_FALT_PEND_SOLICITUD", "DAN_FALT_PEND_TIPO_OBS")
	  REFERENCES "DANIO_FALTANTE_PENDIENTE" ("REG_DAN_FALT_FEC_REP", "REG_DAN_FALT_SOLICITUD", "TIPO_OBS") ENABLE;
	  
