
Insert into DOMINIO (COD_DOMINIO,NOMBRE,ESTADO) values ('1','ESTADO SINIESTRO','1');
Insert into DOMINIO (COD_DOMINIO,NOMBRE,ESTADO) values ('2','ESTADO PAGO SINIESTRO','1');
Insert into DOMINIO (COD_DOMINIO,NOMBRE,ESTADO) values ('3','CONCEPTOS SINIESTRO','1');
Insert into DOMINIO (COD_DOMINIO,NOMBRE,ESTADO) values ('4','ESTADO PENDIENTES','1');
Insert into DOMINIO (COD_DOMINIO,NOMBRE,ESTADO) values ('5','REGLAS NEGOCIO','1');
Insert into DOMINIO (COD_DOMINIO,NOMBRE,ESTADO) values ('6','ESTADO TRANSACCION','1');
Insert into DOMINIO (COD_DOMINIO,NOMBRE,ESTADO) values ('7','MOTIVO AUT DESOCUPACION','1');
insert into INDEMNIZA.DOMINIO values(8, 'Valores IVA', 1);
insert into INDEMNIZA.DOMINIO values(9, 'Valores AMPARO INTEGRAL', 1);
commit;