
CREATE TABLE ADMSISA.RIESGOS_ASEGURADOS 
   (	SOLICITUD NUMBER(10,0) NOT NULL ENABLE, 
		PERIODO VARCHAR2(6 BYTE) NOT NULL ENABLE, 
		AMPARO VARCHAR2(4 BYTE) NOT NULL ENABLE, 
		CONCEPTO VARCHAR2(4 BYTE) NOT NULL ENABLE, 
		VALOR_ASEG NUMBER NOT NULL ENABLE, 
		VALOR_PRIMA NUMBER NOT NULL ENABLE, 
		PRIMA_RETRO NUMBER NOT NULL ENABLE, 
		POLIZA NUMBER(10,0) NOT NULL ENABLE, 
		CONSTRAINT RIES_ASEG_PK PRIMARY KEY (SOLICITUD, PERIODO, AMPARO, CONCEPTO)
);