SET SERVEROUTPUT ON;
DECLARE 
  CURSOR C_SELECT IS SELECT TABLE_NAME  FROM dba_tables WHERE TABLESPACE_NAME = 'SIBO_DATOS' AND OWNER = 'STG_SIBO_QUARTZ';
  CMD   VARCHAR2(200);
BEGIN
  FOR C IN C_SELECT LOOP
  CMD := 'GRANT SELECT , INSERT, UPDATE, DELETE ON STG_SIBO_QUARTZ.' || C.TABLE_NAME || ' TO C_APP_STG_SIBO';
  DBMS_OUTPUT.put_line(CMD);
  EXECUTE IMMEDIATE CMD;
  END LOOP;
END;
/