BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RESUMEN_CARGUE';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_NUMERO_CARGUE_DIARIO';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PARAMETROS_SIBO';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ERROR_CARGUE_LINEA';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_LISTASR';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_UARIV';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_OTROS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MFEA';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SALDOS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TIPO_ARCHIVO';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CONDICIONAL';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DISPE_DIA_DAVIPLATA';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DISPERSION_DAVIPLATA';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RECHAZO';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_REL_PRELIQ_TIPOPAGO';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HIST_ESTADO_PAGO';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HIST_ESTADO_PROCESO';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PROCESO_PAGO';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
--CREATE
CREATE SEQUENCE STG_SIBO.SEQ_CONDICIONAL START WITH 1 INCREMENT BY 1 ;
CREATE SEQUENCE STG_SIBO.SEQ_DISPE_DIA_DAVIPLATA START WITH 1 INCREMENT BY 1 ;
CREATE SEQUENCE STG_SIBO.SEQ_DISPERSION_DAVIPLATA START WITH 1 INCREMENT BY 1 ;
CREATE SEQUENCE STG_SIBO.SEQ_RECHAZO START WITH 1 INCREMENT BY 1 ;
CREATE SEQUENCE STG_SIBO.SEQ_REL_PRELIQ_TIPOPAGO START WITH 1 INCREMENT BY 1 ;
CREATE SEQUENCE STG_SIBO.SEQ_HIST_ESTADO_PAGO START WITH 1 INCREMENT BY 1 ;
CREATE SEQUENCE STG_SIBO.SEQ_HIST_ESTADO_PROCESO START WITH 1 INCREMENT BY 1 ;
CREATE SEQUENCE STG_SIBO.SEQ_PROCESO_PAGO START WITH 1 INCREMENT BY 1 ;

CREATE SEQUENCE  SEQ_RESUMEN_CARGUE  
MINVALUE 1 
MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE  ORDER  NOCYCLE ;

CREATE SEQUENCE  SEQ_NUMERO_CARGUE_DIARIO
MINVALUE 1 
MAXVALUE 999 
INCREMENT BY 1 
START WITH 1 
NOCACHE  
ORDER  NOCYCLE;

CREATE SEQUENCE SEQ_PARAMETROS_SIBO 
INCREMENT BY 1 
MAXVALUE 9999999999999999999999999999 
START WITH 1 
MINVALUE 1;

CREATE SEQUENCE  SEQ_ERROR_CARGUE_LINEA  
MINVALUE 1 
MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 
START WITH 1;

CREATE SEQUENCE SEQ_LISTASR 
INCREMENT BY 1 
START WITH 1 
MINVALUE 1 
MAXVALUE 9999999999999999999999999999 
NOCACHE ORDER;

CREATE SEQUENCE  SEQ_UARIV  
MINVALUE 1 
MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 
START WITH 1 NOCACHE  
ORDER  NOCYCLE;

CREATE SEQUENCE  SEQ_OTROS
MINVALUE 1
MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 
START WITH 1 NOCACHE  
ORDER  NOCYCLE;

CREATE SEQUENCE SEQ_MFEA
MINVALUE 1
MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 
START WITH 1 NOCACHE  
ORDER  NOCYCLE;

CREATE SEQUENCE SEQ_SALDOS
MINVALUE 1
MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 
START WITH 1 NOCACHE  
ORDER  NOCYCLE;

CREATE SEQUENCE SEQ_TIPO_ARCHIVO
MINVALUE 1
MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 
START WITH 1 NOCACHE  
ORDER  NOCYCLE;
