-- WAAB: Se agrega un PARAMETROS_SIBO

insert into PARAMETROS_SIBO (
NOMBRE_PARAMETRO,
VALOR_PARAMETRO,
DESCRIPCION_PARAM)
VALUES (
'ECL_RUTAFICHERO', 
'C:\\GeneracionCSV\\DetalleRechazos\\', 
'RUTA DE GENERACION DE ARCHIVOS PARA LISTAS RESTRICTIVAS'
);





