-- Generado por Oracle SQL Developer Data Modeler 4.1.3.901
--   en:        2016-12-09 09:14:28 COT
--   sitio:     Oracle Database 11g
--   tipo:      Oracle Database 11g
--   Diseñó:    Alfonso Pimienta

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.AUDITORIA' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.PRELIQ_GENERICO' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.LST_RESTRICTIVAS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.WTMP_LST_RESTRICTIVAS_EXT_BAD' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.WTMP_PRELIQ_GENERICO_EXT_BAD';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.WTMP_SALDOS_BAD';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Error_Cargue_Linea CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Listas_R CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Preliq_UARIV CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Preliq_MFEA CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Preliq_OTROS CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.SALDOS CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Procesa_Listas_R CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Procesa_preliq_generico CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Resumen_Cargue CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.Tipo_Archivo CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.PARAMETROS_SIBO CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.CRUCE_RECHAZO_RESUMEN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.ERR$_LST_RESTRICTIVAS20170103';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.ERR$_PRELIQ_GENERICO20170103';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.CONDICIONALES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.MOTIVO_RECHAZO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.AUTENTICACION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.TIPO_DOCUMENTO CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.REL_PRELIQ_TIPOPAGO CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.DISPERSION_DAVIPLATA CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.ESTADO_PAGO CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.ESTADO_PROCESO CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.HIST_ESTADO_PAGO CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.HIST_ESTADO_PROCESO CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE STG_SIBO.PROCESO_PAGO CASCADE CONSTRAINTS' ;
EXCEPTION WHEN OTHERS THEN
NULL;
END;
/
-----------CREATE
CREATE TABLE STG_SIBO.AUDITORIA
   (TIPO VARCHAR2(30 BYTE),
   COD_ERROR VARCHAR2(20 BYTE), 
	"DESCRIPCION" CLOB)	;

  CREATE TABLE STG_SIBO.RESUMEN_CARGUE 
   (	
    IDCARGUE NUMBER(*,0) NOT NULL ENABLE, 
    IDTIPOARCHIVO NUMBER(*,0) NOT NULL ENABLE, 
    FECHA DATE, 
    HORA VARCHAR2(8 BYTE) NOT NULL ENABLE, 
    NUMEROCARGUE NUMBER(*,0) NOT NULL ENABLE, 
    TOTALREGISTROS NUMBER(*,0), 
    TOTALCARGADOS NUMBER(*,0), 
    TOTALERRADOS NUMBER(*,0), 
    NOMBREARCHIVOCARGADO VARCHAR2(40 BYTE), 
    NOMBREARCHIVOEXPORT VARCHAR2(40 BYTE), 
    ID_ESTADO NUMBER(2,0) DEFAULT 0, 
	 CONSTRAINT RESUMEN_CARGUE_PK PRIMARY KEY (IDCARGUE)
   );

CREATE TABLE STG_SIBO.Error_Cargue_Linea
  (
    IDERRORLINEACARGUE INTEGER NOT NULL ,
    IDCARGUE           INTEGER ,
    LINEA              VARCHAR2 (4000 BYTE) NOT NULL ,
    DESCRIPCIONERROR   VARCHAR2 (100 BYTE)
  );
ALTER TABLE STG_SIBO.Error_Cargue_Linea ADD CONSTRAINT Error_Cargue_Linea_PK PRIMARY KEY ( IDERRORLINEACARGUE ) ;

CREATE TABLE STG_SIBO.Listas_R
  (
    IDLISTASR              INTEGER NOT NULL ,
    IDCARGUE               INTEGER NOT NULL ,
    TIPOIDENTIFICACION     VARCHAR2 (10 BYTE) NOT NULL ,
    IDENTIFICACION         NUMBER (16) NOT NULL ,
    IDENTIFICADORNODESEADO VARCHAR2 (3 BYTE)
  );
ALTER TABLE STG_SIBO.Listas_R ADD CONSTRAINT Listas_R_PK PRIMARY KEY ( IDLISTASR ) ;


CREATE TABLE STG_SIBO.PRELIQ_UARIV
   (	
  IDPRELIQ NUMBER(*,0) NOT NULL ENABLE, 
	IDCARGUE NUMBER(*,0) NOT NULL ENABLE, 
	CODMUNICIPIO NUMBER(5,0) NOT NULL ENABLE, 
	DEPARTAMENTO VARCHAR2(60 BYTE), 
	MUNICIPIO VARCHAR2(50 BYTE), 
	CODBENEFICIARIO NUMBER(7,0) NOT NULL ENABLE, 
	NOMBRE1 VARCHAR2(20 BYTE), 
	NOMBRE2 VARCHAR2(20 BYTE), 
	APELLIDO1 VARCHAR2(20 BYTE), 
	APELLIDO2 VARCHAR2(20 BYTE), 
	TIPOID VARCHAR2(2 BYTE) NOT NULL ENABLE, --
	DOCUMENTO NUMBER(12,0) NOT NULL ENABLE, 
	TELEFONO NUMBER(10,0), 
	CELULAR NUMBER(10,0), 
	DIRECCION VARCHAR2(50 BYTE), 
	CORREOELECTRONICO VARCHAR2(50 BYTE), 
	FECHANACIMIENTO DATE, 
	FECHAEXPEDICION DATE, 
	SEXO VARCHAR2(1 BYTE), 
	VALORTOTAL NUMBER(15,0)
  );
ALTER TABLE STG_SIBO.PRELIQ_UARIV ADD CONSTRAINT Preliquidacion_Victimas_PK PRIMARY KEY ( IDPRELIQ ) ;

CREATE TABLE STG_SIBO.Preliq_MFEA
  (
  IDPRELIQ NUMBER(*,0) NOT NULL ENABLE, 
	IDCARGUE NUMBER(*,0) NOT NULL ENABLE, 
	CODMUNICIPIO NUMBER(5,0) NOT NULL ENABLE, 
	DEPARTAMENTO VARCHAR2(60 BYTE), 
	MUNICIPIO VARCHAR2(50 BYTE), 
	CODBENEFICIARIO NUMBER(7,0) NOT NULL ENABLE, 
	NOMBRE1 VARCHAR2(20 BYTE), 
	NOMBRE2 VARCHAR2(20 BYTE), 
	APELLIDO1 VARCHAR2(20 BYTE), 
	APELLIDO2 VARCHAR2(20 BYTE), 
	TIPOID VARCHAR2(2 BYTE) NOT NULL ENABLE, --
	DOCUMENTO NUMBER(12,0) NOT NULL ENABLE, 
	TELEFONO NUMBER(10,0), 
	CELULAR NUMBER(10,0), 
	DIRECCION VARCHAR2(50 BYTE), 
	CORREOELECTRONICO VARCHAR2(50 BYTE), 
	FECHANACIMIENTO DATE, 
	FECHAEXPEDICION DATE, 
	SEXO VARCHAR2(1 BYTE), 
	VALORTOTAL NUMBER(15,0)
  );
ALTER TABLE STG_SIBO.Preliq_MFEA ADD CONSTRAINT Preli_MFEA_PK PRIMARY KEY (IDPRELIQ) ;

CREATE TABLE STG_SIBO.Preliq_OTROS
  (
  IDPRELIQ NUMBER(*,0) NOT NULL ENABLE, 
	IDCARGUE NUMBER(*,0) NOT NULL ENABLE, 
	CODMUNICIPIO NUMBER(5,0) NOT NULL ENABLE, 
	DEPARTAMENTO VARCHAR2(60 BYTE), 
	MUNICIPIO VARCHAR2(50 BYTE), 
	CODBENEFICIARIO NUMBER(7,0) NOT NULL ENABLE, 
	NOMBRE1 VARCHAR2(20 BYTE), 
	NOMBRE2 VARCHAR2(20 BYTE), 
	APELLIDO1 VARCHAR2(20 BYTE), 
	APELLIDO2 VARCHAR2(20 BYTE), 
	TIPOID VARCHAR2(2 BYTE) NOT NULL ENABLE, --
	DOCUMENTO NUMBER(12,0) NOT NULL ENABLE, 
	TELEFONO NUMBER(10,0), 
	CELULAR NUMBER(10,0), 
	DIRECCION VARCHAR2(50 BYTE), 
	CORREOELECTRONICO VARCHAR2(50 BYTE), 
	FECHANACIMIENTO DATE, 
	FECHAEXPEDICION DATE, 
	SEXO VARCHAR2(1 BYTE), 
	VALORTOTAL NUMBER(15,0)
  );
ALTER TABLE STG_SIBO.Preliq_OTROS ADD CONSTRAINT Preli_OTROS_PK PRIMARY KEY ( IDPRELIQ ) ;

CREATE TABLE STG_SIBO.Tipo_Archivo
  (
    IDTIPOARCHIVO     INTEGER NOT NULL ,
    NOMBRETIPOARCHIVO VARCHAR2 (60 BYTE) NOT NULL ,
    SEPARADOR         VARCHAR2 (1 CHAR) NOT NULL ,
    TABLAINSERCION    VARCHAR2 (30 BYTE) NOT NULL,
    IDENTIFICADOR     CHAR(1 BYTE) DEFAULT 1 NOT NULL ENABLE,
    SECUENCIA         VARCHAR2(40 BYTE)
  );
ALTER TABLE STG_SIBO.TIPO_ARCHIVO ADD CONSTRAINT TIPO_ARCHIVO_PK PRIMARY KEY (IDTIPOARCHIVO) ;

CREATE TABLE STG_SIBO.PARAMETROS_SIBO
  (
    ID_PARAMETRO      NUMBER NOT NULL,
    NOMBRE_PARAMETRO  VARCHAR2(60 BYTE) NOT NULL ,
    VALOR_PARAMETRO   VARCHAR2(2000 BYTE) NOT NULL ,
    DESCRIPCION_PARAM VARCHAR2(500 BYTE)
  );
ALTER TABLE PARAMETROS_SIBO ADD CONSTRAINT PARAMETROS_SIBO_PK PRIMARY KEY (ID_PARAMETRO);
ALTER TABLE PARAMETROS_SIBO ADD CONSTRAINT PARAMETROS_SIBO_UK UNIQUE (NOMBRE_PARAMETRO);

CREATE TABLE STG_SIBO.PRELIQ_GENERICO
  (
    ID                NUMBER(*, 0) NOT NULL PRIMARY KEY ,
    CODMUNICIPIO      NUMBER(5, 0) NOT NULL ,
    DEPARTAMENTO      VARCHAR2(60 BYTE) ,
    MUNICIPIO         VARCHAR2(50 BYTE) ,
    CODBENEFICIARIO   NUMBER(7, 0) NOT NULL ,
    NOMBRE1           VARCHAR2(20 BYTE) ,
    NOMBRE2           VARCHAR2(20 BYTE) ,
    APELLIDO1         VARCHAR2(20 BYTE) ,
    APELLIDO2         VARCHAR2(20 BYTE) ,
    TIPOID            VARCHAR2(2 BYTE) ,
    DOCUMENTO         NUMBER(12, 0) NOT NULL ,
    TELEFONO          NUMBER(10, 0) ,
    CELULAR           NUMBER(10, 0) ,
    DIRECCION         VARCHAR2(50 BYTE) ,
    CORREOELECTRONICO VARCHAR2(50 BYTE) ,
    FECHANACIMIENTO   DATE ,
    FECHAEXPEDICION   DATE ,
    SEXO              VARCHAR2(1 BYTE) ,
    VALORTOTAL        NUMBER(15, 0)
  );
  
CREATE TABLE STG_SIBO.LST_RESTRICTIVAS 
(
  IDLISTASR NUMBER(*, 0) NOT NULL 
, TIPOIDENTIFICACION VARCHAR2(10 BYTE) 
, IDENTIFICACION NUMBER(16, 0) 
, IDENTIFICADORNODESEADO VARCHAR2(3 BYTE) 
, CONSTRAINT PROCESA_LISTAS_R_PK PRIMARY KEY ( IDLISTASR )
);

CREATE TABLE STG_SIBO.AUTENTICACION
   (	
  "USERNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(200 BYTE), 
	"PRIMER_NOMBRE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"SEGUNDO_NOMBRE" VARCHAR2(100 BYTE), 
	"PRIMER_APELLIDO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"SEGUNDO_APELLIDO" VARCHAR2(100 BYTE), 
	 CONSTRAINT "AUTENTICACION_PK" PRIMARY KEY ("USERNAME")
);

CREATE TABLE STG_SIBO.MOTIVO_RECHAZO
   (	
  IDRECHAZO NUMBER PRIMARY KEY, 
	DESCRIPCION VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	ESTADORECHAZO NUMBER(1,0) DEFAULT 2 NOT NULL ENABLE, 
  CONSTRAINT ESTADORECHAZO_CK CHECK (ESTADORECHAZO IN(2, 3)) ENABLE
  );

CREATE TABLE STG_SIBO.CRUCE_RECHAZO_RESUMEN
  (
    IDRECHAZO NUMBER,
    IDCARGUE  NUMBER,
    CONSTRAINT CRUCE_RECHAZO_PK PRIMARY KEY (IDRECHAZO, IDCARGUE),
    CONSTRAINT CRUCE_RECHAZO_FK FOREIGN KEY (IDCARGUE) REFERENCES RESUMEN_CARGUE (IDCARGUE) ON DELETE CASCADE ENABLE
  );

CREATE TABLE STG_SIBO.SALDOS
   (	
  IDSALDO NUMBER NOT NULL ENABLE, 
	IDCARGUE NUMBER NOT NULL ENABLE, 
	BIN NUMBER(9,0), 
	NITEMPRESA NUMBER(15,0), 
	IDDAVIPLATA NUMBER(19,0) NOT NULL ENABLE, 
	MIEMBRO NUMBER(3,0), 
	NOMBRETITULAR VARCHAR2(27 BYTE), 
	SALDODISPONIBLE NUMBER(17,2), 
	ESTADOTARJETA VARCHAR2(3 BYTE), 
	DESCRIPCIONESTADO VARCHAR2(30 BYTE), 
	SUBTIPO VARCHAR2(3 BYTE), 
	TIPOID VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	DOCUMENTO NUMBER(15,0) NOT NULL ENABLE, 
	ORIGENCREACION VARCHAR2(1 BYTE), 
	CONSTRAINT SALDOS_PK PRIMARY KEY (IDSALDO),
  CONSTRAINT "SALDOS_UK" UNIQUE ("IDCARGUE", "TIPOID", "DOCUMENTO"));

CREATE TABLE STG_SIBO.CONDICIONALES 
(
  IDCONDICIONAL NUMBER NOT NULL
, IDCARGUE NUMBER NOT NULL 
, TIPOID VARCHAR2(2 BYTE) NOT NULL
, DOCUMENTO NUMBER(12) NOT NULL
, TIPOPAGO NUMBER(1) NOT NULL
, CONSTRAINT CONDICIONALES_PK PRIMARY KEY ( IDCONDICIONAL )
, CONSTRAINT RESUMEN_CARGUE_CONDICIONAL_FK FOREIGN KEY (IDCARGUE) REFERENCES STG_SIBO.RESUMEN_CARGUE (IDCARGUE) ON DELETE CASCADE ENABLE
); 

CREATE TABLE STG_SIBO.TIPO_DOCUMENTO 
(
  TIPOID VARCHAR2(2 BYTE) NOT NULL 
, DESCRIPCION VARCHAR2(50 BYTE) NOT NULL 
, CONSTRAINT TIPO_DOCUMENTO_PK PRIMARY KEY ( TIPOID )
, CONSTRAINT TIPO_DOCUMENTO_UK UNIQUE ( DESCRIPCION )
);

CREATE TABLE STG_SIBO.REL_PRELIQ_TIPOPAGO 
  (
  IDRELPRELIQ NUMBER, 
	IDCARGUE NUMBER NOT NULL ENABLE, 
	IDPRELIQ NUMBER(38,0) NOT NULL ENABLE, 
	IDTIPOPAGO NUMBER(1,0) NOT NULL ENABLE, 
	 CONSTRAINT REL_PRELIQ_CARGUE_PK PRIMARY KEY ( IDRELPRELIQ )
);

CREATE TABLE STG_SIBO.DISPERSION_DAVIPLATA 
   (	
    "ID_DIS_DAVIPLATA" NUMBER(38,0), 
    "IDCARGUE" NUMBER(38,0), 
    "NIT_EMPRESA" VARCHAR2(15 BYTE), 
    "FECHA_ENVIO" NUMBER(8,0), 
    "CONSECUTIVO_ENVIO" VARCHAR2(5 BYTE), 
    "TIPO_IDENTIFICACION" VARCHAR2(2 BYTE), 
    "NUM_IDENTIFICACION_CLI" VARCHAR2(15 BYTE), 
    "NUMERO_TARJETA" VARCHAR2(19 BYTE), 
    "NUMERO_CUENTA" VARCHAR2(19 BYTE), 
    "TIPO_NOVEDAD" VARCHAR2(1 BYTE), 
    "VALOR_NOVEDAD" VARCHAR2(17 BYTE), 
    "INDICADOR_MENSAJE" VARCHAR2(1 BYTE), 
    "DISPONIBLE" VARCHAR2(27 BYTE), 
    "CODIGO_ERROR" VARCHAR2(3 BYTE), 
	 CONSTRAINT "DISP_DAVIPLATA_PK" PRIMARY KEY ("ID_DIS_DAVIPLATA")
);

  CREATE TABLE STG_SIBO.ESTADO_PAGO
   (	
    "ID_EST_PAGO" NUMBER(2,0) NOT NULL ENABLE, 
    "DES_EST_PAGO" VARCHAR2(100 BYTE), 
    CONSTRAINT "ESTADO_PAGO_PK" PRIMARY KEY (ID_EST_PAGO)
    );

CREATE  TABLE STG_SIBO.ESTADO_PROCESO
  (
    ID_ESTADO  NUMBER (2) NOT NULL ,
    DES_ESTADO VARCHAR2 (100 BYTE),
    CONSTRAINT ESTADO_PROCESO_PK PRIMARY KEY (ID_ESTADO )
  ) ;

CREATE  TABLE STG_SIBO.HIST_ESTADO_PAGO
  (
    ID_HIST_PAGO NUMBER (38) NOT NULL ,
    ID_PROC_PAGO NUMBER (38) NOT NULL ,
    ID_EST_PAGO  NUMBER (2) NOT NULL ,
    USERNAME     VARCHAR2 (50) ,
    FECHA        DATE,
    CONSTRAINT HIST_EST_PAGO_PK PRIMARY KEY (ID_HIST_PAGO )
  ) ;

CREATE  TABLE STG_SIBO.HIST_ESTADO_PROCESO
  (
    ID_HISTORIA NUMBER (38) NOT NULL ,
    IDCARGE     NUMBER (38) ,
    ID_ESTADO   NUMBER (2) NOT NULL ,
    USERNAME    VARCHAR2 (50) ,
    FECHA       DATE,
    CONSTRAINT HIST_ESTADO_PROCESO_PK PRIMARY KEY ( ID_HISTORIA )
  ) ;

CREATE
  TABLE STG_SIBO.PROCESO_PAGO
  (
    ID_PROC_PAGO   NUMBER (38) NOT NULL ,
    IDCARGUE       NUMBER (38) ,
    IDTIPOPAGO     NUMBER (1) ,
    NOMBRE_ARCHIVO VARCHAR2 (100) ,
    ID_EST_PAGO    NUMBER (2) NOT NULL ,
    FECHA_ENVIO    DATE,
    CONSTRAINT PROCESO_PAGO_PK PRIMARY KEY (ID_PROC_PAGO )
  ) ;

ALTER TABLE STG_SIBO.Error_Cargue_Linea ADD CONSTRAINT Error_Cargue_Linea_Resumen_FK FOREIGN KEY ( IDCARGUE ) REFERENCES STG_SIBO.Resumen_Cargue ( IDCARGUE ) ON DELETE CASCADE ;
--ALTER TABLE STG_SIBO.CONDICIONALES ADD CONSTRAINT RESUMEN_CARGUE_CONDICIONAL_FK FOREIGN KEY (IDCARGUE) REFERENCES STG_SIBO.RESUMEN_CARGUE (IDCARGUE) ON DELETE CASCADE ENABLE ;
ALTER TABLE STG_SIBO.CONDICIONALES ADD CONSTRAINT TIPO_DOCUMENTO_CONDICIONAL_FK FOREIGN KEY (TIPOID)   REFERENCES STG_SIBO.TIPO_DOCUMENTO (TIPOID)   ON DELETE CASCADE ENABLE ;
ALTER TABLE STG_SIBO.CONDICIONALES ADD CONSTRAINT CONDICIONALES_UK UNIQUE (TIPOID,DOCUMENTO,IDCARGUE);
ALTER TABLE STG_SIBO.CONDICIONALES ADD CONSTRAINT CONDICIONALES_CK CHECK  (TIPOPAGO IN(1,2,3));
ALTER TABLE STG_SIBO.RESUMEN_CARGUE ADD CONSTRAINT RES_CAR_ESTADO_FK FOREIGN KEY (ID_ESTADO)  REFERENCES STG_SIBO.ESTADO_PROCESO (ID_ESTADO);
ALTER TABLE STG_SIBO.Listas_R ADD CONSTRAINT Listas_R_Resumen_FK FOREIGN KEY ( IDCARGUE ) REFERENCES Resumen_Cargue ( IDCARGUE ) ON DELETE CASCADE ;
ALTER TABLE STG_SIBO.PRELIQ_UARIV ADD CONSTRAINT PRELIQ_AURIV_Resumen_FK FOREIGN KEY ( IDCARGUE ) REFERENCES Resumen_Cargue ( IDCARGUE ) ON DELETE CASCADE ;
ALTER TABLE STG_SIBO.PRELIQ_MFEA ADD CONSTRAINT PRELIQ_MFEA_Resumen_FK FOREIGN KEY ( IDCARGUE ) REFERENCES Resumen_Cargue ( IDCARGUE ) ON DELETE CASCADE ;
ALTER TABLE STG_SIBO.PRELIQ_OTROS ADD CONSTRAINT PRELIQ_OTROS_Resumen_FK FOREIGN KEY ( IDCARGUE ) REFERENCES Resumen_Cargue ( IDCARGUE ) ON DELETE CASCADE ;
ALTER TABLE STG_SIBO.Resumen_Cargue ADD CONSTRAINT Resumen_Tipo_Archivo_FK FOREIGN KEY ( IDTIPOARCHIVO ) REFERENCES Tipo_Archivo ( IDTIPOARCHIVO ) ON DELETE CASCADE ;

ALTER TABLE STG_SIBO.HIST_ESTADO_PAGO ADD CONSTRAINT HIST_EST_PAG_EST_PAG_FK FOREIGN KEY( ID_EST_PAGO ) REFERENCES STG_SIBO.ESTADO_PAGO ( ID_EST_PAGO ) ;
ALTER TABLE STG_SIBO.HIST_ESTADO_PAGO ADD CONSTRAINT HIST_EST_PAG_PROC_PAG_FK FOREIGN KEY ( ID_PROC_PAGO ) REFERENCES STG_SIBO.PROCESO_PAGO ( ID_PROC_PAGO ) ;
ALTER TABLE STG_SIBO.HIST_ESTADO_PROCESO ADD CONSTRAINT HIST_EST_PROC_EST_PROC_FK FOREIGN KEY ( ID_ESTADO ) REFERENCES STG_SIBO.ESTADO_PROCESO ( ID_ESTADO ) ;
ALTER TABLE STG_SIBO.PROCESO_PAGO ADD CONSTRAINT PROC_PAG_EST_PAG_FK FOREIGN KEY (ID_EST_PAGO ) REFERENCES STG_SIBO.ESTADO_PAGO ( ID_EST_PAGO ) ;
