-------------------------------------LISTAS_R
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_ERROR_LISTAS_R', 'ERR$_LST_RESTRICTIVAS', 'PREFIJO DE TABLA TEMPORAL ERRORES LISTAS_R');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_BAD_LISTAS_R', 'WTMP_LST_RESTRICTIVAS_EXT_BAD', 'PREFIJO DE TABLA TEMPORAL BAD LISTAS_R');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEM_STAGE_LISTAS_R', 'LST_RESTRICTIVAS', 'PREFIJO DE TABLA TEMPORAL STAGE LISTAS_R');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('COLUMNAS_TABLA_DESTINO_LISTAS_R', '1 AS IDLISTASR, 1 AS IDCARGUE, TIPOIDENTIFICACION,  IDENTIFICACION,  IDENTIFICADORNODESEADO', 'CAMPOS PARA EL SELECT DE LISTAS_R');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TIPO_RECORD_LISTAS_R', 'LISTAS_R%ROWTYPE', 'VARIABLE DE TIPO ROWTYPE DE LISTAS_R');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TABLA_DE_DESTINO_LISTAS_R', 'LISTAS_R', 'TABLA DE NEGOCIO LISTAS RESTRICITVAS');
COMMIT;
/*
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CURSORES_CADENA_LISTAS_R', 'TIPO_RECORD.TIPOIDENTIFICACION || ''',''' || TIPO_RECORD.IDENTIFICACION || ''',''' || TIPO_RECORD.IDENTIFICADORNODESEADO || '''';', 'CADENA AUXILIAR PARA INSERT DE LISTAS RESTRITIVAS');
COMMIT;
*/
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CURSORES_CADENA_LISTAS_R', 
'TIPO_RECORD.TIPOIDENTIFICACION || '''''','''''' || TIPO_RECORD.IDENTIFICACION || '''''','''''' || TIPO_RECORD.IDENTIFICADORNODESEADO || '''';', 
'CADENA AUXILIAR PARA INSERT DE LISTAS RESTRITIVAS');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CADENA_CONCATENA_ERROR_LISTAS_R', 'TIPOIDENTIFICACION || ''''|'''' || IDENTIFICACION || ''''|'''' ||  IDENTIFICADORNODESEADO, NVL(DESCRIPCION , ''''SIN DESCRIPCION'''')', 'CADENA AUXILIAR PARA INSERT ERROR EN ERROR CARGUE LINEA');
COMMIT;

--PRELIQUIDACION
-------------------------------------UARIV
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_ERROR_UARIV', 'ERR$_PRELIQ_GENERICO', 'PREFIJO DE TABLA TEMPORAL ERRORES PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_BAD_UARIV', 'WTMP_PRELIQ_GENERICO_EXT_BAD', 'PREFIJO DE TABLA TEMPORAL BAD PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEM_STAGE_UARIV', 'PRELIQ_GENERICO', 'PREFIJO DE TABLA TEMPORAL STAGE PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('COLUMNAS_TABLA_DESTINO_UARIV', '1 AS IDPRELIQ, 1 AS IDCARGUE,CODMUNICIPIO,DEPARTAMENTO,MUNICIPIO,CODBENEFICIARIO,NOMBRE1,NOMBRE2,APELLIDO1,APELLIDO2,TIPOID,DOCUMENTO,TELEFONO,CELULAR,DIRECCION,CORREOELECTRONICO,FECHANACIMIENTO,FECHAEXPEDICION,SEXO,VALORTOTAL', 'CAMPOS PARA EL SELECT DE PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TIPO_RECORD_UARIV', 'PRELIQ_GENERICO%ROWTYPE', 'VARIABLE DE TIPO ROWTYPE DE PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TABLA_DE_DESTINO_UARIV', 'PRELIQ_UARIV', 'TABLA DE NEGOCIO OTRAS PRELIQUIDACIONES');
COMMIT;
/*
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CURSORES_CADENA_UARIV', 'NVL(TIPO_RECORD.CODMUNICIPIO,'') || ''',''' || NVL(TIPO_RECORD.DEPARTAMENTO,'') || ''',''' || NVL(TIPO_RECORD.MUNICIPIO,'') || ''',''' || NVL(TIPO_RECORD.CODBENEFICIARIO,'') || ''',''' || NVL(TIPO_RECORD.NOMBRE1,'') || ''',''' || NVL(TIPO_RECORD.NOMBRE2,'') || ''',''' || NVL(TIPO_RECORD.APELLIDO1,'') || ''',''' || NVL(TIPO_RECORD.APELLIDO2,'') || ''',''' || NVL(TIPO_RECORD.TIPOID,'') || ''',' || NVL(TIPO_RECORD.DOCUMENTO,'') || ',' || NVL(TIPO_RECORD.TELEFONO,'') || ',' || NVL(TIPO_RECORD.CELULAR,'') || ',''' || NVL(TIPO_RECORD.DIRECCION,'') || ''',''' || NVL(TIPO_RECORD.CORREOELECTRONICO,'')  || ''',''' || NVL(TIPO_RECORD.FECHANACIMIENTO,'')  || ''',''' || NVL(TIPO_RECORD.FECHAEXPEDICION,'') || ''',''' || NVL(TIPO_RECORD.SEXO,'') || ''',' || NVL(TIPO_RECORD.VALORTOTAL,0);', 'CADENA AUXILIAR PARA INSERT DE OTRAS PRELIQUIDACIONES');
COMMIT;
*/
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CURSORES_CADENA_UARIV', 
'NVL(TIPO_RECORD.CODMUNICIPIO,'') || '''''','''''' || NVL(TIPO_RECORD.DEPARTAMENTO,'') || '''''','''''' || NVL(TIPO_RECORD.MUNICIPIO,'') || '''''','''''' || NVL(TIPO_RECORD.CODBENEFICIARIO,'') || '''''','''''' || NVL(TIPO_RECORD.NOMBRE1,'') || '''''','''''' || NVL(TIPO_RECORD.NOMBRE2,'') || '''''','''''' || NVL(TIPO_RECORD.APELLIDO1,'') || '''''','''''' || NVL(TIPO_RECORD.APELLIDO2,'') || '''''','''''' || NVL(TIPO_RECORD.TIPOID,'') || '''''','' || NVL(TIPO_RECORD.DOCUMENTO,'') || '','' || NVL(TIPO_RECORD.TELEFONO,'') || '','' || NVL(TIPO_RECORD.CELULAR,'') || '','''''' || NVL(TIPO_RECORD.DIRECCION,'') || '''''','''''' || NVL(TIPO_RECORD.CORREOELECTRONICO,'')  || '''''','''''' || NVL(TIPO_RECORD.FECHANACIMIENTO,'')  || '''''','''''' || NVL(TIPO_RECORD.FECHAEXPEDICION,'') || '''''','''''' || NVL(TIPO_RECORD.SEXO,'') || '''''','' || NVL(TIPO_RECORD.VALORTOTAL,0);', 
'CADENA AUXILIAR PARA INSERT DE OTRAS PRELIQUIDACIONES');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CADENA_CONCATENA_ERROR_UARIV', 
'NVL(CODMUNICIPIO,NULL) ||
''''|'''' || NVL(DEPARTAMENTO,NULL) || 
''''|'''' || NVL(MUNICIPIO,NULL) || 
''''|'''' || NVL(CODBENEFICIARIO,NULL) || 
''''|'''' || NVL(NOMBRE1,NULL) || 
''''|'''' || NVL(NOMBRE2,NULL) || 
''''|'''' || NVL(APELLIDO1,NULL) || 
''''|'''' || NVL(APELLIDO2,NULL) || 
''''|'''' || NVL(TIPOID,NULL) || 
''''|'''' || NVL(DOCUMENTO,NULL) || 
''''|'''' || NVL(TELEFONO,NULL) || 
''''|'''' || NVL(CELULAR,NULL) || 
''''|'''' || NVL(DIRECCION,NULL) || 
''''|'''' || NVL(CORREOELECTRONICO,NULL)  || 
''''|'''' || NVL(FECHANACIMIENTO,NULL)  || 
''''|'''' || NVL(FECHAEXPEDICION,NULL) || 
''''|'''' || NVL(SEXO,NULL) || 
''''|'''' || NVL(VALORTOTAL,0) LINEA, NVL(DESCRIPCION , ''''SIN DESCRIPCION'''')', 
'CADENA AUXILIAR PARA INSERT ERROR UARIV EN ERROR CARGUE LINEA');
COMMIT;

-------------------------------------MFEA
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_ERROR_MFEA', 'ERR$_PRELIQ_GENERICO', 'PREFIJO DE TABLA TEMPORAL ERRORES PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_BAD_MFEA', 'WTMP_PRELIQ_GENERICO_EXT_BAD', 'PREFIJO DE TABLA TEMPORAL BAD PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEM_STAGE_MFEA', 'PRELIQ_GENERICO', 'PREFIJO DE TABLA TEMPORAL STAGE PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('COLUMNAS_TABLA_DESTINO_MFEA', '1 AS IDULTIMAPRELIQUIDACION, 1 AS IDCARGUE,CODMUNICIPIO,DEPARTAMENTO,MUNICIPIO,CODBENEFICIARIO,NOMBRE1,NOMBRE2,APELLIDO1,APELLIDO2,TIPOID,DOCUMENTO,TELEFONO,CELULAR,DIRECCION,CORREOELECTRONICO,FECHANACIMIENTO,FECHAEXPEDICION,SEXO,VALORTOTAL', 'CAMPOS PARA EL SELECT DE PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TIPO_RECORD_MFEA', 'PRELIQ_GENERICO%ROWTYPE', 'VARIABLE DE TIPO ROWTYPE DE PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TABLA_DE_DESTINO_MFEA', 'PRELIQ_MFEA', 'TABLA DE NEGOCIO OTRAS PRELIQUIDACIONES');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CURSORES_CADENA_MFEA', 'TIPO_RECORD.CODMUNICIPIO || '''''','''''' || TIPO_RECORD.DEPARTAMENTO || '''''','''''' || TIPO_RECORD.MUNICIPIO || '''''','''''' || TIPO_RECORD.CODBENEFICIARIO || '''''','''''' || TIPO_RECORD.NOMBRE1 || '''''','''''' || TIPO_RECORD.NOMBRE2 || '''''','''''' || TIPO_RECORD.APELLIDO1 || '''''','''''' || TIPO_RECORD.APELLIDO2 || '''''','''''' || TIPO_RECORD.TIPOID || '''''','' || TIPO_RECORD.DOCUMENTO || '','' || TIPO_RECORD.TELEFONO || '','' || TIPO_RECORD.CELULAR || '','''''' || TIPO_RECORD.DIRECCION || '''''','''''' || TIPO_RECORD.CORREOELECTRONICO  || '''''','''''' || TIPO_RECORD.FECHANACIMIENTO  || '''''','''''' || TIPO_RECORD.FECHAEXPEDICION || '''''','''''' || TIPO_RECORD.SEXO || '''''','' || TIPO_RECORD.VALORTOTAL;', 'CADENA AUXILIAR PARA INSERT DE OTRAS PRELIQUIDACIONES');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CADENA_CONCATENA_ERROR_MFEA', 
'NVL(CODMUNICIPIO,NULL) ||
''''|'''' || NVL(DEPARTAMENTO,NULL) || 
''''|'''' || NVL(MUNICIPIO,NULL) || 
''''|'''' || NVL(CODBENEFICIARIO,NULL) || 
''''|'''' || NVL(NOMBRE1,NULL) || 
''''|'''' || NVL(NOMBRE2,NULL) || 
''''|'''' || NVL(APELLIDO1,NULL) || 
''''|'''' || NVL(APELLIDO2,NULL) || 
''''|'''' || NVL(TIPOID,NULL) || 
''''|'''' || NVL(DOCUMENTO,NULL) || 
''''|'''' || NVL(TELEFONO,NULL) || 
''''|'''' || NVL(CELULAR,NULL) || 
''''|'''' || NVL(DIRECCION,NULL) || 
''''|'''' || NVL(CORREOELECTRONICO,NULL)  || 
''''|'''' || NVL(FECHANACIMIENTO,NULL)  || 
''''|'''' || NVL(FECHAEXPEDICION,NULL) || 
''''|'''' || NVL(SEXO,NULL) || 
''''|'''' || NVL(VALORTOTAL,0) LINEA, NVL(DESCRIPCION , ''''SIN DESCRIPCION'''')', 
'CADENA AUXILIAR PARA INSERT ERROR UARIV EN ERROR CARGUE LINEA');
COMMIT;

-------------------------------------OTROS
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_ERROR_OTROS', 'ERR$_PRELIQ_GENERICO', 'PREFIJO DE TABLA TEMPORAL ERRORES PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_BAD_OTROS', 'WTMP_PRELIQ_GENERICO_EXT_BAD', 'PREFIJO DE TABLA TEMPORAL BAD PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEM_STAGE_OTROS', 'PRELIQ_GENERICO', 'PREFIJO DE TABLA TEMPORAL STAGE PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('COLUMNAS_TABLA_DESTINO_OTROS', '1 AS IDULTIMAPRELIQUIDACION, 1 AS IDCARGUE,CODMUNICIPIO,DEPARTAMENTO,MUNICIPIO,CODBENEFICIARIO,NOMBRE1,NOMBRE2,APELLIDO1,APELLIDO2,TIPOID,DOCUMENTO,TELEFONO,CELULAR,DIRECCION,CORREOELECTRONICO,FECHANACIMIENTO,FECHAEXPEDICION,SEXO,VALORTOTAL', 'CAMPOS PARA EL SELECT DE PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TIPO_RECORD_OTROS', 'PRELIQ_GENERICO%ROWTYPE', 'VARIABLE DE TIPO ROWTYPE DE PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TABLA_DE_DESTINO_OTROS', 'PRELIQ_OTROS', 'TABLA DE NEGOCIO OTRAS PRELIQUIDACIONES');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CURSORES_CADENA_OTROS', 'TIPO_RECORD.CODMUNICIPIO || '''''','''''' || TIPO_RECORD.DEPARTAMENTO || '''''','''''' || TIPO_RECORD.MUNICIPIO || '''''','''''' || TIPO_RECORD.CODBENEFICIARIO || '''''','''''' || TIPO_RECORD.NOMBRE1 || '''''','''''' || TIPO_RECORD.NOMBRE2 || '''''','''''' || TIPO_RECORD.APELLIDO1 || '''''','''''' || TIPO_RECORD.APELLIDO2 || '''''','''''' || TIPO_RECORD.TIPOID || '''''','' || TIPO_RECORD.DOCUMENTO || '','' || TIPO_RECORD.TELEFONO || '','' || TIPO_RECORD.CELULAR || '','''''' || TIPO_RECORD.DIRECCION || '''''','''''' || TIPO_RECORD.CORREOELECTRONICO  || '''''','''''' || TIPO_RECORD.FECHANACIMIENTO  || '''''','''''' || TIPO_RECORD.FECHAEXPEDICION || '''''','''''' || TIPO_RECORD.SEXO || '''''','' || TIPO_RECORD.VALORTOTAL;', 'CADENA AUXILIAR PARA INSERT DE OTRAS PRELIQUIDACIONES');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CADENA_CONCATENA_ERROR_OTROS', 
'NVL(CODMUNICIPIO,NULL) ||
''''|'''' || NVL(DEPARTAMENTO,NULL) || 
''''|'''' || NVL(MUNICIPIO,NULL) || 
''''|'''' || NVL(CODBENEFICIARIO,NULL) || 
''''|'''' || NVL(NOMBRE1,NULL) || 
''''|'''' || NVL(NOMBRE2,NULL) || 
''''|'''' || NVL(APELLIDO1,NULL) || 
''''|'''' || NVL(APELLIDO2,NULL) || 
''''|'''' || NVL(TIPOID,NULL) || 
''''|'''' || NVL(DOCUMENTO,NULL) || 
''''|'''' || NVL(TELEFONO,NULL) || 
''''|'''' || NVL(CELULAR,NULL) || 
''''|'''' || NVL(DIRECCION,NULL) || 
''''|'''' || NVL(CORREOELECTRONICO,NULL)  || 
''''|'''' || NVL(FECHANACIMIENTO,NULL)  || 
''''|'''' || NVL(FECHAEXPEDICION,NULL) || 
''''|'''' || NVL(SEXO,NULL) || 
''''|'''' || NVL(VALORTOTAL,0) LINEA, NVL(DESCRIPCION , ''''SIN DESCRIPCION'''')', 
'CADENA AUXILIAR PARA INSERT ERROR UARIV EN ERROR CARGUE LINEA');
COMMIT;

-------------------------------------SALDOS
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_ERROR_SALDOS', 'ERR$_SALDOS', 'PREFIJO DE TABLA TEMPORAL ERRORES SALDOS');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEMP_BAD_SALDOS', 'WTMP_SALDOS_EXT_BAD', 'PREFIJO DE TABLA TEMPORAL BAD SALDOS');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('PREFIJO_TABLA_TEM_STAGE_SALDOS', 'SALDOS_TEM', 'PREFIJO DE TABLA TEMPORAL STAGE SALDOS');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('COLUMNAS_TABLA_DESTINO_SALDOS', '1 AS IDSALDOS, 1 AS IDCARGUE,BIN,NITEMPRESA,IDDAVIPLATA,MIEMBRO,NOMBRETITULAR,SALDODISPONIBLE,ESTADOTARJETA,DESCRIPCIONESTADO,SUBTIPO,TIPOID,DOCUMENTO,ORIGENCREACION', 'CAMPOS PARA EL SELECT DE PRELIQ_GENERICO');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TIPO_RECORD_SALDOS', 'SALDOS%ROWTYPE', 'VARIABLE DE TIPO ROWTYPE DE SALDOS');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('TABLA_DE_DESTINO_SALDOS', 'SALDOS', 'TABLA DE NEGOCIO SALDOS');
COMMIT;

/*
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CURSORES_CADENA_SALDOS', 'TIPO_RECORD.CODMUNICIPIO || '''''','''''' || TIPO_RECORD.DEPARTAMENTO || '''''','''''' || TIPO_RECORD.MUNICIPIO || '''''','''''' || TIPO_RECORD.CODBENEFICIARIO || '''''','''''' || TIPO_RECORD.NOMBRE1 || '''''','''''' || TIPO_RECORD.NOMBRE2 || '''''','''''' || TIPO_RECORD.APELLIDO1 || '''''','''''' || TIPO_RECORD.APELLIDO2 || '''''','''''' || TIPO_RECORD.TIPOID || '''''','' || TIPO_RECORD.DOCUMENTO || '','' || TIPO_RECORD.TELEFONO || '','' || TIPO_RECORD.CELULAR || '','''''' || TIPO_RECORD.DIRECCION || '''''','''''' || TIPO_RECORD.CORREOELECTRONICO  || '''''','''''' || TIPO_RECORD.FECHANACIMIENTO  || '''''','''''' || TIPO_RECORD.FECHAEXPEDICION || '''''','''''' || TIPO_RECORD.SEXO || '''''','' || TIPO_RECORD.VALORTOTAL;', 'CADENA AUXILIAR PARA INSERT DE SALDOS');
COMMIT;
*/
INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CURSORES_CADENA_SALDOS'
,'NVL(TIPO_RECORD.BIN,'''') || '''''','' || NVL(TIPO_RECORD.NITEMPRESA,'''') || '','' || NVL(TIPO_RECORD.IDDAVIPLATA,'''') || '','' || 
	NVL(TIPO_RECORD.MIEMBRO,'''') || '','''''' || NVL(TIPO_RECORD.NOMBRETITULAR,'''') || '''''','' || NVL(TIPO_RECORD.SALDODISPONIBLE,'''') || '','''''' || 
	NVL(TIPO_RECORD.ESTADOTARJETA,'''') || '''''','''''' || NVL(TIPO_RECORD.DESCRIPCIONESTADO,'''') || '''''','''''' || NVL(TIPO_RECORD.SUBTIPO,'''') || '''''','''''' || 
	NVL(TIPO_RECORD.TIPOID,'''') || '''''','' || NVL(TIPO_RECORD.DOCUMENTO,'''') || '','''''' || NVL(TIPO_RECORD.ORIGENCREACION,'''') || '''''''';'
, 'CADENA AUXILIAR PARA INSERT DE SALDOS');
COMMIT;

INSERT INTO PARAMETROS_SIBO (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CADENA_CONCATENA_ERROR_SALDOS', 'NVL(BIN,NULL) || ''''''|'''' || NVL(NITEMPRESA,NULL) || 
''''|'''' || NVL(MUNICIPIO,NULL) || 
''''|'''' || NVL(IDDAVIPLATA,NULL) || 
''''|'''' || NVL(MIEMBRO,NULL) || 
''''|'''' || NVL(NOMBRETITULAR,NULL) || 
''''|'''' || NVL(SALDODISPONIBLE,NULL) || 
''''|'''' || NVL(ESTADOTARJETA,NULL) || 
''''|'''' || NVL(DESCRIPCIONESTADO,NULL) || 
''''|'''' || NVL(SUBTIPO,NULL) || 
''''|'''' || NVL(TIPOID,NULL) || 
''''|'''' || NVL(DOCUMENTO,NULL) || 
''''|'''' || NVL(ORIGENCREACION,NULL) LINEA, NVL(DESCRIPCION , ''''SIN DESCRIPCION'''')',
'CADENA AUXILIAR PARA INSERT ERROR EN ERROR CARGUE LINEA');
COMMIT;

-------------------------------------

--INSERT PARA AGREGAR ARCHIVOS DE CARGUE EN EL SISTEMA
INSERT INTO TIPO_ARCHIVO 
  (
    NOMBRETIPOARCHIVO,
    SEPARADOR,
    TABLAINSERCION,
    IDENTIFICADOR,
    SECUENCIA
  )
VALUES ('LISTAS RESTRICTIVAS', ';', 'LISTAS_R', 1, 'SEQ_LISTASR');
COMMIT;

INSERT INTO TIPO_ARCHIVO 
  (
    NOMBRETIPOARCHIVO,
    SEPARADOR,
    TABLAINSERCION,
    IDENTIFICADOR,
    SECUENCIA
  )
VALUES ('PRELIQUIDACION UARIV', ';', 'UARIV', 2, 'SEQ_UARIV');
COMMIT;

INSERT INTO TIPO_ARCHIVO 
  (
    NOMBRETIPOARCHIVO,
    SEPARADOR,
    TABLAINSERCION,
    IDENTIFICADOR,
    SECUENCIA
  )
VALUES ('PRELIQUIDACION MFEA', ';', 'MFEA', 3, '	SEQ_MFEA');
COMMIT;

INSERT INTO TIPO_ARCHIVO 
  (
    NOMBRETIPOARCHIVO,
    SEPARADOR,
    TABLAINSERCION,
    IDENTIFICADOR,
    SECUENCIA
  )
VALUES ('PRELIQUIDACION OTROS', ';', 'OTROS', 4, 'SEQ_OTROS');
COMMIT;
