--------------------------------------------------------
--  Ref Constraints for Table AUTORIZACION_DESOCUPACIOON
--------------------------------------------------------

  ALTER TABLE INDEMNIZA.AUTORIZACION_DESOCUPACIOON ADD CONSTRAINT AUTO_DESO_DESO_PEND_FK FOREIGN KEY (DESO_PEND_TIPO_OBS, DESO_PEND_DESOC_FEC_REGI, DESO_PEND_DESOC_SOLICITUD)
	  REFERENCES INDEMNIZA.DESOCUPACION_PENDIENTE (TIPO_OBS, DESOCUPACION_FEC_REGI, DESOCUPACION_SOLICITUD) ENABLE;
	  
