--------------------------------------------------------
--  Ref Constraints for Table AUTORIZACION_INDEMNIZACION
--------------------------------------------------------

  ALTER TABLE INDEMNIZA.AUTORIZACION_INDEMNIZACION ADD CONSTRAINT AUTO_INDEM_SINIESTRO_PEND_FK FOREIGN KEY (SINI_PEND_SINIE_FEC_REP, SINI_PEND_SINIE_SOLICITUD, SINI_PEND_TIP_OBS) REFERENCES INDEMNIZA.SINIESTRO_PENDIENTE (SINIESTRO_FEC_REP, SINIESTRO_SOLICITUD, TIP_OBS) ENABLE;
  
