SET SERVEROUTPUT ON;
DECLARE 
  CURSOR C_SELECT IS SELECT TABLE_NAME  FROM USER_TABLES WHERE TABLESPACE_NAME = 'SIBO_DATOS';
  CMD   VARCHAR2(200);
BEGIN
  FOR C IN C_SELECT LOOP
  CMD := 'GRANT SELECT , INSERT, UPDATE, DELETE ON STG_SIBO.' || C.TABLE_NAME || ' TO C_APP_STG_SIBO';
  DBMS_OUTPUT.put_line(CMD);
  EXECUTE IMMEDIATE CMD;
  END LOOP;
END;
/
DECLARE 
  CURSOR C_SELECT IS SELECT DISTINCT U.OBJECT_NAME FROM USER_PROCEDURES U WHERE OBJECT_TYPE IN ('PACKAGE', 'PROCEDURE');
  CMD   VARCHAR2(200);
BEGIN
  FOR C IN C_SELECT LOOP
  CMD := 'GRANT EXECUTE ON STG_SIBO.' || C.OBJECT_NAME || ' TO C_APP_STG_SIBO';
  DBMS_OUTPUT.put_line(CMD);
  EXECUTE IMMEDIATE CMD;
  END LOOP;
END;
/
DECLARE 
  CURSOR C_SELECT IS SELECT U.SEQUENCE_NAME FROM SYS.USER_SEQUENCES U;
  CMD   VARCHAR2(200);
BEGIN
  FOR C IN C_SELECT LOOP
  CMD := 'GRANT SELECT ON STG_SIBO.' || C.SEQUENCE_NAME || ' TO C_APP_STG_SIBO';
  DBMS_OUTPUT.put_line(CMD);
  EXECUTE IMMEDIATE CMD;
  END LOOP;
END;
/
