UPDATE "STG_SIBO"."PARAMETROS_SIBO" SET VALOR_PARAMETRO = '/GeneracionCSV/DetalleRechazos/' WHERE NOMBRE_PARAMETRO= 'ECL_RUTAFICHERO';

UPDATE "STG_SIBO"."PARAMETROS_SIBO" SET VALOR_PARAMETRO = '90.4.0.184' WHERE NOMBRE_PARAMETRO='FTP_HOST';

UPDATE "STG_SIBO"."PARAMETROS_SIBO" SET VALOR_PARAMETRO = '/oracle/weblogic/GeneracionCSV/Preliquidacion/' WHERE NOMBRE_PARAMETRO='PRELIQUIDACION_RUTAFICHERO';

UPDATE "STG_SIBO"."PARAMETROS_SIBO" SET VALOR_PARAMETRO = '/export/home/crmcarga/GeneracionCSV/Preliquidacion/' WHERE NOMBRE_PARAMETRO='FTP_PATH';

UPDATE PARAMETROS_SIBO SET VALOR_PARAMETRO = '
NVL(BIN,NULL) || 
''''|'''' || NVL(NITEMPRESA,NULL) || 
''''|'''' || NVL(MUNICIPIO,NULL) || 
''''|'''' || NVL(IDDAVIPLATA,NULL) || 
''''|'''' || NVL(MIEMBRO,NULL) || 
''''|'''' || NVL(NOMBRETITULAR,NULL) || 
''''|'''' || NVL(SALDODISPONIBLE,NULL) || 
''''|'''' || NVL(ESTADOTARJETA,NULL) || 
''''|'''' || NVL(DESCRIPCIONESTADO,NULL) || 
''''|'''' || NVL(SUBTIPO,NULL) || 
''''|'''' || NVL(TIPOID,NULL) || 
''''|'''' || NVL(DOCUMENTO,NULL) || 
''''|'''' || NVL(ORIGENCREACION,NULL) LINEA, NVL(ORA_ERR_MESG$ , ''''SIN DESCRIPCION'''')
'
WHERE NOMBRE_PARAMETRO='CADENA_CONCATENA_ERROR_SALDOS';

INSERT INTO "STG_SIBO"."PARAMETROS_SIBO" (NOMBRE_PARAMETRO, VALOR_PARAMETRO, DESCRIPCION_PARAM) 
VALUES ('CONSTANTE_REGISTROS_ERROR_ESTRUCTURA', '''Error de estructura o datos''', 'Constante para error generico de registros sin descripción - tabla BAD');

commit;




