CREATE OR REPLACE TRIGGER TIPO_ARCHIVO_TRG
BEFORE INSERT ON TIPO_ARCHIVO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDTIPOARCHIVO IS NULL THEN
      SELECT SEQ_TIPO_ARCHIVO.NEXTVAL INTO :NEW.IDTIPOARCHIVO FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END TIPO_ARCHIVO_TRG;
/