--------------------------------------------------------
--  Ref Constraints for Table AUTORIZACION_OPERACION
--------------------------------------------------------

  ALTER TABLE "AUTORIZACION_OPERACION" ADD CONSTRAINT "AUTO_OPER_AUM_PEND_FK" FOREIGN KEY ("AUM_PEND_AUM_FEC_AUMENTO", "AUM_PEND_AUME_SOLICITUD", "AUM_PEND_TIPO_OBS_AUM")
	  REFERENCES "AUMENTO_PENDIENTE" ("AUMENTO_FEC_AUMENTO", "AUMENTO_SOLICITUD", "TIPO_OBS_AUM") ENABLE;
  ALTER TABLE "AUTORIZACION_OPERACION" ADD CONSTRAINT "AUTO_OPER_ING_PEND_FK" FOREIGN KEY ("ING_PEND_INGR_FEC_REGISTRO_ING", "ING_PEND_INGR_SOLICITUD", "ING_PEND_TIPO_OBS_ING")
	  REFERENCES "INGRESO_PENDIENTE" ("INGRESO_FEC_REGISTRO_ING", "INGRESO_SOLICITUD", "TIPO_OBS_ING") ENABLE;
