--------------------------------------------------------
--  Ref Constraints for Table AUTORIZACION_INDEMNIZACION
--------------------------------------------------------

  ALTER TABLE "AUTORIZACION_INDEMNIZACION" ADD CONSTRAINT "AUTO_INDEM_SINIESTRO_PEND_FK" FOREIGN KEY ("SINI_PEND_SINIE_FEC_REP", "SINI_PEND_SINIE_SOLICITUD", "SINI_PEND_TIP_OBS")
	  REFERENCES "SINIESTRO_PENDIENTE" ("SINIESTRO_FEC_REP", "SINIESTRO_SOLICITUD", "TIP_OBS") ENABLE;
  ALTER TABLE "AUTORIZACION_INDEMNIZACION" ADD CONSTRAINT "AUTO_IND_DANIO_FALT_PEND_FK" FOREIGN KEY ("DAN_FALT_PEND_FEC_REP", "DAN_FALT_PEND_SOLICITUD", "DAN_FALT_PEND_TIPO_OBS")
	  REFERENCES "DANIO_FALTANTE_PENDIENTE" ("REG_DAN_FALT_FEC_REP", "REG_DAN_FALT_SOLICITUD", "TIPO_OBS") ENABLE;
