--------------------------------------------------------
--  Ref Constraints for Table TRANSACCION
--------------------------------------------------------

  ALTER TABLE "TRANSACCION" ADD CONSTRAINT "TRANSACCION_AUMENTO_FK" FOREIGN KEY ("AUMENTO_FEC_AUMENTO", "AUM_SOLICITUD_SAI_SOLICITUD")
	  REFERENCES "AUMENTO" ("FEC_AUMENTO", "SOLICITUD_SAI_SOLICITUD") ENABLE;
  ALTER TABLE "TRANSACCION" ADD CONSTRAINT "TRANSACCION_DESISTIMIENTO_FK" FOREIGN KEY ("DESISTIMIENTO_FEC_REG", "DESIS_SOL_SAI_SOLICITUD")
	  REFERENCES "DESISTIMIENTO" ("FEC_REG", "SOLICITUD_SAI_SOLICITUD") ENABLE;
  ALTER TABLE "TRANSACCION" ADD CONSTRAINT "TRANSACCION_DESOCUPACION_FK" FOREIGN KEY ("DESOCUPACION_FEC_REGI", "DESO_SOLICITUD_SAI_SOLICITUD")
	  REFERENCES "DESOCUPACION" ("FEC_REGI", "SOLICITUD_SAI_SOLICITUD") ENABLE;
  ALTER TABLE "TRANSACCION" ADD CONSTRAINT "TRANSACCION_INGRESO_FK" FOREIGN KEY ("INGRESO_FEC_REGISTRO_ING", "ING_SOLICITUD_SAI_SOLICITUD")
	  REFERENCES "INGRESO" ("FEC_REGISTRO_ING", "SOLICITUD_SAI_SOLICITUD") ENABLE;
  ALTER TABLE "TRANSACCION" ADD CONSTRAINT "TRANSACCION_RETIRO_FK" FOREIGN KEY ("RETIRO_FECHA_RETIRO", "RETI_SOLICITUD_SAI_SOLICITUD")
	  REFERENCES "RETIRO" ("FECHA_RETIRO", "SOLICITUD_SAI_SOLICITUD") ENABLE;
  ALTER TABLE "TRANSACCION" ADD CONSTRAINT "TRANSACCION_SINIESTRO_FK" FOREIGN KEY ("SINIESTRO_FEC_REP", "SINIESTRO_SOL_SAI_SOLICITUD")
	  REFERENCES "SINIESTRO" ("FEC_REP", "SOLICITUD_SAI_SOLICITUD") ENABLE;
  ALTER TABLE "TRANSACCION" ADD CONSTRAINT "TRAN_LOG_SERV_SIMI_FK" FOREIGN KEY ("LOG_SERV_SIMI_COD_LOG_SERV")
	  REFERENCES "LOG_SERVICIO_SIMI" ("COD_LOG_SERV") ENABLE;
  ALTER TABLE "TRANSACCION" ADD CONSTRAINT "TRAN_REG_AMP_INT_FK" FOREIGN KEY ("REG_AMPARO_INTEGRAL_FEC_REP", "REG_AMP_INTE_SOL_SAI_SOLICITUD")
	  REFERENCES "REGISTRO_AMPARO_INTEGRAL" ("FEC_REP", "SOLICITUD_SAI_SOLICITUD") ENABLE;
  ALTER TABLE "TRANSACCION" ADD CONSTRAINT "TRAN_REG_DAN_FALT_FK" FOREIGN KEY ("REG_DANIO_FALT_FEC_REP", "REG_DAN_FAL_SOL_SAI_SOLICITUD")
	  REFERENCES "REGISTRO_DANIO_FALTANTE" ("FEC_REP", "SOLICITUD_SAI_SOLICITUD") ENABLE;
